### ISSUE TITLE
[bug]保存之后污染数据

### ISSUE THREAD

**Issue by chengs** [sunnylqm/react-native-storage#1]
调用了 save 方法之后，原数据会被污染，加上了一个 expires 的属性。
建议在 save 的时候，不改动原始数据，而是做一个深度拷贝。

**Comment by sunnylqm** [comment]
原先只单独对基本数据类型wrap了一层，没注意这个问题，我再统一wrap一层好了。

**Comment by sunnylqm** [comment]
fixed  https://github.com/sunnylqm/react-native-storage/commit/c74626dd7a82c969deb591acd09f4c2bb357375f

**Comment by sunnylqm** [comment]
@chengs  注意，此次修改后，由于数据结构变化，之前保存的数据将无法读取

**Comment by chengs** [comment]
好的！
