### ISSUE TITLE
读取储存的数据太慢了

### ISSUE THREAD

**Issue by yang515648779** [sunnylqm/react-native-storage#10]
React Native程序完全退出，进去后读取储存的数据太慢了，至少要半分钟，还没用过官方的，不知道是不是官方的读取也很慢

**Comment by sunnylqm** [comment]
贴一下代码吧。半分钟有点不可思议。

**Comment by yang515648779** [comment]
试了下官方的一样的慢，那可能是使用redux框架的原因，可能哪里写得不对

**Comment by sunnylqm** [comment]
大量异步过程同步执行了？

**Comment by yang515648779** [comment]
自己换回RN官方的，也很慢，然后又换回这个库，速度竟然自己又好了。好神奇呀
