### ISSUE TITLE
how i can return a promise

### ISSUE THREAD

**Issue by zhaixiaoou** [sunnylqm/react-native-storage#100]
I want to encapsulated into a class ,  and call the method 
![e9dd97fa-fcce-434b-9b2c-793aec4690d5](https://cloud.githubusercontent.com/assets/9987397/26679860/71899e5a-4709-11e7-8065-71675dc2aa90.png)
![fc3a1a4b-0b2c-4b18-ab7b-d750c8ba4425](https://cloud.githubusercontent.com/assets/9987397/26679870/7e0266a8-4709-11e7-8d69-3cd6ed560f58.png)

when i call this method , how to get the result? also have the correct result and error

**Comment by sunnylqm** [comment]
add `return `  before 'storage.load' in your 'load' function
