### ISSUE TITLE
about storage backend? 

### ISSUE THREAD

**Issue by zhaixiaoou** [sunnylqm/react-native-storage#102]
use function sync to storage backend? but my key is  a variable。
I see the doc ,but i dont know how to do. i am so sorry. i need your help .
![7767875c-7c26-4f57-bf1e-9cb6f3909435](https://cloud.githubusercontent.com/assets/9987397/26716281/6572effc-47ab-11e7-9ec9-979c8a2b468f.png

![a3c0d70d-91bf-4882-9420-5331b4486af4](https://cloud.githubusercontent.com/assets/9987397/26716312/81b091f6-47ab-11e7-99f4-c29454255929.png)

![be39e90e-032a-44f1-ab29-ec42b4de6416](https://cloud.githubusercontent.com/assets/9987397/26716382/be95eb98-47ab-11e7-8a09-6620a7ec6554.png)
![46c953ff-0723-45a7-9422-b3206b43ad0e](https://cloud.githubusercontent.com/assets/9987397/26716397/ce12fe1c-47ab-11e7-8bbf-40fcddb5d8fc.png)

thank you !!

**Comment by sunnylqm** [comment]
where is your init code

**Comment by sunnylqm** [comment]
And I really don't know what is unclear in doc

![qq20170602-170820](https://cloud.githubusercontent.com/assets/615282/26719147/f61a37a4-47b5-11e7-9956-5abebc0d5c4f.png)

**Comment by zhaixiaoou** [comment]
no attention ! sorry  😓
