### ISSUE TITLE
storage.save怎么分KEY存储我需要多个KEY存储不同的数据

### ISSUE THREAD

**Issue by search-inner** [sunnylqm/react-native-storage#106]
请问有提供类似AsyncStoreage里的multiSet方法

**Comment by sunnylqm** [comment]
还没有。你可以自己写循环去save

**Comment by search-inner** [comment]
好的，那后续有打算开发这个方法吗

**Comment by sunnylqm** [comment]
没觉得有什么必要

**Comment by kage-ssd** [comment]
Hi how to save with numeric key ?

eg.

 const projectID:string = String('myProjects'+123123)
 
storage.save({
        key: projectID, 
        data: [],
        expires: 3650000 * 3600
      });
