### ISSUE TITLE
读取数据的时候没有读到数据的话需要在.then里面传处理reject状态的函数

### ISSUE THREAD

**Issue by zk2401** [sunnylqm/react-native-storage#107]
storage.load({key:'userInfo'}).then(
            ret=>{this.setState({isLogin:1})},rejct=>{
                this.setState({isLogin:2})
            }
        )

直接catch的话会提示有没有处理的reject，是不是我的用法有问题，这里第二个函数里面是处理没读到userinfo这个情况的

**Comment by sunnylqm** [comment]
没看懂你的问题

**Comment by zk2401** [comment]
@sunnylqm 注意看下上面读取的代码，和文档里面的不一样，我按文档的写法在没读到数据的时候会出问题

**Comment by sunnylqm** [comment]
出什么问题你贴出来啊
