### ISSUE TITLE
data is lost after refresh

### ISSUE THREAD

**Issue by barron9** [sunnylqm/react-native-storage#108]
why data is not saving after app close and reopen?

**Comment by sunnylqm** [comment]
no storageBackend?

**Comment by barron9** [comment]
i am using exact same as demo i don't get red errors but simple data is not found after refresh...

**Comment by sunnylqm** [comment]
Post your code here.
storageBackend is not required, so there won't be red errors.

**Comment by sunnylqm** [comment]
// Use AsyncStorage for RN, or window.localStorage for web.
	// If not set, data would be lost after reload.

**Comment by barron9** [comment]
i have tried async storage , but still loses data, `alert(JSON.stringify(AsyncStorage.getItem('loginState')));`
with 
`AsyncStorage.setItem('loginState', 'ss');`

**Comment by sunnylqm** [comment]
AsyncStorage is a `async` storage, so it does not have a direct return value. It must be used with `await` prepend, or with `then` append.

**Comment by barron9** [comment]
thanks yes i have solved the issue
