### ISSUE TITLE
SOS， syncInBackground false 设置不走sync 获取数据更新了。

### ISSUE THREAD

**Issue by kmend** [sunnylqm/react-native-storage#110]
react-native-storage  在 0.2.2 版本中  syncInBackground false 不走 sync 获取数据了， 只能设置存储时过期时间，
RN 版本 0.44.3

**Comment by sunnylqm** [comment]
贴代码

**Comment by kmend** [comment]
import { AsyncStorage } from "react-native";
import Storage from "react-native-storage";

const storage = new Storage({

    // 最大容量，默认值1000条数据循环存储
    size: 100000,

    // 数据过期时间，默认一整天（1000 * 3600 * 24 毫秒），设为null则永不过期
    defaultExpires: 1000 * 3600 * 24,

    // 存储引擎：对于RN使用AsyncStorage，对于web使用window.localStorage
    // 如果不指定则数据只会保存在内存中，重启后即丢失
    storageBackend: AsyncStorage,

    // 读写时在内存中缓存数据。默认启用。
    enableCache: true,
    
    // 如果storage中没有相应数据，或数据已过期，
    // 则会调用相应的sync同步方法，无缝返回最新数据。
    sync: {
        UserInfo(params){

            let { resolve, syncParams} = params;
            let testRes = { testID: 1 };
            console.log( "USERINFO RES SYNC ==> ", testRes );
            resolve(testRes);
            storage.save({
                "key": 'UserInfo',
                "rawData": testRes,
            });

        },
    },
    
});


storage.load({key: "UserInfo" , autoSync: true, syncInBackground: false }).then((testRes)=>{
    console.log( "USERINFO RES 1==>",  testRes );
    storage.load({key: "UserInfo" , autoSync: true, syncInBackground: false }).then((testRes)=>{
        console.log( "USERINFO RES 2==>",  testRes );
    });
});
    

输出结果
 'USERINFO RES SYNC ==> ', { testID: 1 }
 'USERINFO RES 1==>', { testID: 1 }
 'USERINFO RES 2==>', { testID: 1 }
  
// 第一次能正确走 sync, 往后的请求设置  syncInBackground 无效
期望结果
 'USERINFO RES SYNC ==> ', { testID: 1 }
 'USERINFO RES 1==>', { testID: 1 }
 'USERINFO RES SYNC ==> ', { testID: 1 }
 'USERINFO RES 2==>', { testID: 1 }

**Comment by sunnylqm** [comment]
你数据没到过期时间不会触发sync

**Comment by sunnylqm** [comment]
// syncInBackground(默认为true)意味着如果数据过期，
    // 在调用sync方法的同时先返回已经过期的数据。
    // 设置为false的话，则始终强制返回sync方法提供的最新数据(当然会需要更多等待时间)。

不管是true或者false，前提都是数据过期

**Comment by kmend** [comment]
，那是我理解错了， 也就是说要是需要更新数据，得先清下当前key的数据了吧~

**Comment by sunnylqm** [comment]
是的，要么设置很短的过期时间，要么手动调用sync方法

**Comment by kmend** [comment]
明白了， 谢谢~
