### ISSUE TITLE
咨询一下目前的存储上限逻辑？

### ISSUE THREAD

**Issue by wenkangzhou** [sunnylqm/react-native-storage#111]
目前看文档是1000条数据自动循环，但这样还是可能爆掉，因为localstorage上限是5M，AsyncStorage好像也只有6M,是否有一个机制是判断容量上限，删除过期时间临近的数据？另外判断的时机是什么时候？

**Comment by sunnylqm** [comment]
localStorage的上限是5m，但是AsyncStorage应该没有明确上限
目前没有别的机制防爆

**Comment by NewStartMe** [comment]
爆掉 有什么后果呢？所有数据都会丢失 还是只有超过上限的数据存储不上？

**Comment by sunnylqm** [comment]
会抛出异常无法写入

**Comment by sunnylqm** [comment]
@NewStartMe 我这里只管条数，至于你一条一个字还是一条一个T，我这里都管不着。

**Comment by NewStartMe** [comment]
@sunnylqm   好的 非常感谢您的回答
