### ISSUE TITLE
能不能提供一个完整地demo?

### ISSUE THREAD

**Issue by NikiLee2016** [sunnylqm/react-native-storage#116]
关于sync这个重要的属性的用法看得云里雾里.... 在自己的项目设置了storage.sync = {...}也没生效. 求大神说得详细一点或者提供一个完整一点的demo..

**Comment by sunnylqm** [comment]
文档里就是完整的例子啊

**Comment by xiaochanghai** [comment]
我按照您的例子来写，麻烦请教一下怎么获取能同步拿到数据参数

**Comment by sunnylqm** [comment]
什么叫同步拿到数据参数

**Comment by xiaochanghai** [comment]
@sunnylqm 我想要吧storage.load封装在一个方法里面，然后直接返回

**Comment by xiaochanghai** [comment]
![image](https://user-images.githubusercontent.com/25529268/28702305-b82a9f06-738e-11e7-9a1c-53c9f4799923.png)

**Comment by xiaochanghai** [comment]
麻烦赐教一下

**Comment by sunnylqm** [comment]
我在中文文档里专门强调过了
对于异步方法，只能以promise的.then的形式链式调用，或者使用async/await语法调用，至于具体怎么用，请自己学习相关语法
