### ISSUE TITLE
使用getAllDataForKey方法查询某个key下的所有数据会报错

### ISSUE THREAD

**Issue by IrenaChou** [sunnylqm/react-native-storage#117]
我设置的是key都相同id不同
**# 使用getAllDataForKey方法查询某个key下的所有数据会报下面这个错，查询都有问题**
YellowBox.js:71 Possible Unhandled Promise Rejection (id: 0):
ExpiredError {
  "message": "Expired! Params:  此处后面是本地存储的数据

**# 用load方法查报如下错**
Not Found! Params: 

查某个key下的所有id没问题
// 获取某个key下的所有id
storage.getIdsForKey('user').then(ids => {
    console.log(ids);
});

// 获取某个key下的所有数据
storage.getAllDataForKey('user').then(users => {
    console.log(users);
});

**Comment by sunnylqm** [comment]
最好给个能重现的demo

**Comment by IrenaChou** [comment]
在下面的链接里
保存的代码在 **src->disvocer->wangyi->DiscoverListScene** 里
获取代码在 **src->history->HistoryScene**


[demo](http://pan.baidu.com/s/1sl0lohZ)
密码:gj4y

**Comment by sunnylqm** [comment]
你直接把代码文本贴到这里

**Comment by IrenaChou** [comment]
index.ios.js
import storage from './src/common/storage'

storage
---
import Storage from 'react-native-storage';
import { AsyncStorage } from 'react-native';


var storage = new Storage({
    size: 1000,
    storageBackend: AsyncStorage,
    defaultExpires: 1000 * 3600 * 24,
    enableCache: true,
})
global.storage = storage;

保存【是一个listview，点击cell的时候走这个保存】
---
function saveReadNewsToLocation(rowData){
    storage.save({
        key: "news",  // 注意:请不要在key中使用_下划线符号!common.storyKey
        id: rowData.docid,   // 注意:请不要在id中使用_下划线符号!
        data: rowData,
        expires: 1000 * 60
    });
}

获取【是一个listview，当下拉刷新时获取缓存】
----
      storage.getAllDataForKey('news').then(news => {
          console.log("===="+news);
          console.log("\n\n\n\n\n");
      });

**Comment by sunnylqm** [comment]
你配置了expires却没有配置对应的sync，所以会有这个报错
要么你配置不过期，要么你配置个对应的sync方法（哪怕是空函数）即可解决

**Comment by IrenaChou** [comment]
问题1.  我将storage中的defaultExpires改成不过期，保存时也为expires设置了永不过期，还是会报一样的错误
问题2.  我在上次给你看的代码storage中配置了如下代码，其它地方都不动，也还是会报一样的错误
`
sync: {}
`


下面是 ***问题1* 中的代码
-----
index.ios.js
---
import storage from './src/common/storage'

storage
---
import Storage from 'react-native-storage';
import { AsyncStorage } from 'react-native';


var storage = new Storage({
    size: 1000,
    storageBackend: AsyncStorage,
    defaultExpires: null,
    enableCache: true
})
global.storage = storage;

保存【是一个listview，点击cell的时候走这个保存】
---
```
function saveReadNewsToLocation(rowData){
    storage.save({
        key: "news",  // 注意:请不要在key中使用_下划线符号!common.storyKey
        id: rowData.docid,   // 注意:请不要在id中使用_下划线符号!
        data: rowData,
        expires: null
    });
}
```


获取【是一个listview，当下拉刷新时获取缓存】
----
```
      storage.getAllDataForKey('news').then(news => {
          console.log("===="+news);
          console.log("\n\n\n\n\n");
      });
```

**Comment by sunnylqm** [comment]
https://github.com/sunnylqm/react-native-storage/blob/master/storage.js#L205
在node_modules/react-native-storage/storage.js的205行加上断点，然后看下代码后续的执行过程

**Comment by IrenaChou** [comment]
并没有走storage.js的205行的方法
从storage.js【331】-->【156】-》core.js【42，127】-》JSTimers.js【117，120，198..】-》MessageQueue.js【222】后面没有跟了

**Comment by sunnylqm** [comment]
错了。。。是241行

**Comment by IrenaChou** [comment]
!!!  可以了，感谢您的耐心解答，应该是之前存储的数据过期了，我把以前的本地存储数据清空掉又重新去存储，获取，可以了，感谢感谢感谢感谢感谢感谢感谢感谢...
