### ISSUE TITLE
How to use storage to find thru items?

### ISSUE THREAD

**Issue by cajoy** [sunnylqm/react-native-storage#12]
For example I have list of items and want to find one with particular name / or pattern

What is the best way to achieve it? May be some docs would be good?

**Comment by sunnylqm** [comment]
I think I've given some explanation and usagefor "key-only" data and ''key-id" data in the doc. So what specific problem do you encounter?

**Comment by sunnylqm** [comment]
I am closing this issue. Feel free to reopen it if you are still in doubt.
