### ISSUE TITLE
OsdStorage.load({})里面取到的值，赋值不了全局变量，求教

### ISSUE THREAD

**Issue by tibic** [sunnylqm/react-native-storage#121]
class testDemo{
   value = null
    constructor() {
    }
    init() {
            this.getValue().then(()=>{
               console.log(this.value); // 获取不到
            }).catch(function(error){
                console.error(error);
            });
    }
    getValue() {
        return new Promise((resolve,reject)=>{
            OsdStorage.load({
                key: key
            }).then(data => {
                 this.value = data;
            }).catch(err => {
                switch (err.name) {
                    case 'NotFoundError':
                    break;
                    case 'ExpiredError':
                    break;
                }
            })
    }
}

**Comment by sunnylqm** [comment]
你需要学习promise的返回值
