### ISSUE TITLE
如何关闭提示信息？

### ISSUE THREAD

**Issue by loseway** [sunnylqm/react-native-storage#124]
如果没有找到数据，设备底部会报黄条警告Not Found！Params{。。。。}，可以开关关闭么？

**Comment by sunnylqm** [comment]
http://reactnative.cn/docs/0.48/debugging.html#%E5%BA%94%E7%94%A8%E5%86%85%E7%9A%84%E9%94%99%E8%AF%AF%E4%B8%8E%E8%AD%A6%E5%91%8A%E6%8F%90%E7%A4%BA-%E7%BA%A2%E5%B1%8F%E5%92%8C%E9%BB%84%E5%B1%8F-
