### ISSUE TITLE
getBatchData doesnt work?

### ISSUE THREAD

**Issue by Tom29** [sunnylqm/react-native-storage#126]
It works while i load it separately.
```
storage.load({ key: 'settings' })
storage.load({ key: 'currentCity' })
```

Now i need to load data with multiple keys, it return `NotFoundError` error even one of them is exist ?!

```
storage.getBatchData([
	{ key: 'settings' },
	{ key: 'currentCity' },
])
```

**Comment by Tom29** [comment]
I found out that while using `getBatchData`, if one of them was not found, it returns nothing.
This is wrong, it should return the found result for existing keys and error for not exist keys

**Comment by sunnylqm** [comment]
This happened because you have configured `expires` but without counter `sync` methods.
So either specify expires to null, or give a counter sync method, even an empty function is OK.

**Comment by Tom29** [comment]
@sunnylqm I already set `defaultExpires: null` , removed `sync : {}`, reseted all data.
And still didn't work

**Comment by sunnylqm** [comment]
post your complete code here
