### ISSUE TITLE
保存成功后是不是不能回调callback？

### ISSUE THREAD

**Issue by SemperChen** [sunnylqm/react-native-storage#129]

**Comment by sunnylqm** [comment]
什么意思？

**Comment by SemperChen** [comment]
static setItem(key: string, value: string, callback?: ?(error: ?Error) => void)
我的意思是可不可传入官方API所说的第三个参数callback回调呢

**Comment by sunnylqm** [comment]
不能。这里都promise化了，不接受老式的callback，建议尽快熟悉promise/async/await的写法。

**Comment by SemperChen** [comment]
好的，感谢
