### ISSUE TITLE
How to check if the key exist?

### ISSUE THREAD

**Issue by pacozaa** [sunnylqm/react-native-storage#134]
How to check if the key exist?

**Comment by pacozaa** [comment]
I am trying to resolve value out of `catch` but it also make error. I want to know how to check if it is exist outside `catch`

**Comment by sunnylqm** [comment]
something like
```
function safeLoad(options) {
  return storage.load(options).catch(e => {
    // .......
  })
}
```

**Comment by pacozaa** [comment]
@sunnylqm I have  tried it but it still break the process in Expo.

**Comment by sunnylqm** [comment]
post your code here

**Comment by pacozaa** [comment]
There you go
``` javascript
export const loadLogin = () => {
  return new Promise(function (resolve, reject) {
    storage.load({
      key: 'login',
    }).then(ret => {
      resolve(ret)
    }).catch(err => {
      console.warn(err.message)
      if (err.name == 'NotFoundError') {
        resolve('notfound')
      }
    })
  })
}
```

**Comment by pacozaa** [comment]
A little bit out of topic but my `loadLogin` above called by async/await function.
@sunnylqm just read https://github.com/sunnylqm/react-native-storage/blob/ffd71974670ed1d369dbe04e22cbb6dab46c5ef7/storage.js#L302
load function here. The `load()` itself return a promise. So it means that `loadLogin` function above can be async/await as well. No need to use `Promise` inside `loadLogin`. Am I correct?

**Comment by sunnylqm** [comment]
You don't need an extra promise and its resolve/reject. But you do need to add `return` before storage.load

**Comment by pacozaa** [comment]
Like this?
``` javascript
export const loadLogin = async (overtime) =>{
  return await storage.load({
    key: 'login'
  })
}
```

**Comment by sunnylqm** [comment]
Since you want no interrupting errors then you need to add `try/catch` around storage.load
