### ISSUE TITLE
开发中，reload之后获取不到值，杀掉进程重启又获取到了

### ISSUE THREAD

**Issue by danna88** [sunnylqm/react-native-storage#135]
经常出现上述问题，不知道什么原因？
谢谢！

**Comment by sunnylqm** [comment]
请详细说明

**Comment by danna88** [comment]
公司不能联网，我手打一下代码。
在Loginscreen.js页面中，有如下代码：

componentDidMount({
    storage.load ( {
        key:'loginUser',
    } ).then(data =>{
        this.setState({
            username:data.username
        } )
    } ).catch ( (err) =>{
        this.setState (xxxxx);
    } )


代码没写全。
遇到的问题就是，例如我登录成功之后，reload，回到登录界面（我还没做自动登录），发现上述那段代码没有正确执行，debug跟踪之后发现，没有进去then或者catch里面。
但是我杀掉进程，再次进去又有返回值了，而且这个时候在这个界面reload就一直有值，不知道怎么回事！

**Comment by danna88** [comment]
另外再说明一下，貌似发布包没有这个问题，只在开发中会有

**Comment by sunnylqm** [comment]
rn什么版本，是否处在chrome debug环境中

**Comment by danna88** [comment]
0.48.2的RN版本，没有处在chrome debug环境中，就是处于chrome debug中，也同样获取不到

**Comment by sunnylqm** [comment]
如果也没有任何报错，我看不出任何问题
可以尝试一下官方的AsyncStorage，看是否存在同样的情况

**Comment by sfratini** [comment]
Random English comment passing through

**Comment by danna88** [comment]
官方的也一样，困惑中！

**Comment by 495640129** [comment]
中文： 我也遇到了类似的情况，初始化方法new Storage之后，执行读取方法storage.load不会执行到then和catch里面，很困惑
React-Native 版本: 0.50.0

english：
I also encountered a similar situation, initialization method after new Storage, execute read method Storage. The load will not perform to then and catch it, confused
React-Native version : 0.50.0

**Comment by 495640129** [comment]
@sfratini @sunnylqm  
上面的问题看一下，困惑几天了
Let's take a look at it for a few days

**Comment by 495640129** [comment]
ios上没有这个问题，android上就有这个问题
There's no problem with ios, and there's this issue on android

**Comment by sunnylqm** [comment]
@495640129 看起来是rn官方的问题，请去rn官方issue提问

**Comment by sunnylqm** [comment]
似乎和这个有关 https://github.com/facebook/react-native/issues/14101

**Comment by danna88** [comment]
嗯，那就是RN组件的bug了。

**Comment by huqiliang** [comment]
不会进入then 不会执行之后的语句，杀进程后重启又可以看到

**Comment by lizhuoyuan** [comment]
+1
