### ISSUE TITLE
大神，我这是什么错啊，能帮忙看一下吗，一直搞不清

### ISSUE THREAD

**Issue by SemperChen** [sunnylqm/react-native-storage#141]
以下console出来的错误：
Expired! Params: {"ret":{"rawData":{"tag":"51d11e782de6405c45000068","bookName":"大主宰","chapterName":"第1章 北灵院","currentChapterNum":1,"pageNum":1,"totalPage":14,"image":"http://statics.zhuishushenqi.com/agent/http%3A%2F%2Fimg.1391.com%2Fapi%2Fv1%2Fbookcenter%2Fcover%2F1%2F41569%2F_41569_056809.jpg%2F","siteName":"追书神器网","id":"51d11e782de6405c45000068","lastReadTime":1510584522360},"expires":1510670922360},"key":"bookmark","id":"51d11e782de6405c45000068","autoSync":true,"syncInBackground":true}

**Comment by SemperChen** [comment]
噢😯，好像是数据过期了，是这样吗

**Comment by sunnylqm** [comment]
看文档
