### ISSUE TITLE
no update() ? so stupid!

### ISSUE THREAD

**Issue by 12343954** [sunnylqm/react-native-storage#144]
load() and save() to update() ？
so strong a library ，can not update cache directly！
waste too much time

**Comment by ishsingh** [comment]
12343954 Your response was extremely rude. This is an open source project. If you are missing something why don't you add it to the library for everyone's benefit.

**Comment by frxncisjoseph** [comment]
**This using the save() function without mutating the state or anything else for that matter.**

Anyhow, no need for the nonconstructive issue, it's an open source project.
They're no developers at your bidding, this is something that you could do.
