### ISSUE TITLE
Remove Item

### ISSUE THREAD

**Issue by Vincenzo1997** [sunnylqm/react-native-storage#145]
When I remove an item, appear this screen:
![screen shot 2017-12-05 at 14 51 51](https://user-images.githubusercontent.com/34278520/33616521-5e1b013a-d9dd-11e7-8700-ddf88f488c71.png)
But the system works, I dismiss and the object is remove, how can I fix it?

**Comment by sunnylqm** [comment]
post your code here

**Comment by Vincenzo1997** [comment]
`const rimuovi = (<TouchableOpacity style={{
      flex: 1,
      flexDirection: 'row',
      margin: 10
     }}
     onPress = { () => {
      storage.clearMapForKey('Evento'+varId);
      Alert.alert(
        'Evento Rimosso!!',
         [
          {text: 'OK', onPress: () => this.setState({display: aggiungi})},
         ],
         { cancelable: false }
        );
     }
     }
     >
    <Icon name='remove-circle-outline' type='content' color='red'/>
    <Text style={styles.bodyText}>  Rimuovi dai miei eventi</Text>
   </TouchableOpacity>);`

**Comment by sunnylqm** [comment]
看起来像是alert写错了

**Comment by Vincenzo1997** [comment]
Sorry man can you write in english?

**Comment by Vincenzo1997** [comment]
Thanks man, now is working!!! 👍
