### ISSUE TITLE
cannot find the variable

### ISSUE THREAD

**Issue by sjmjulia** [sunnylqm/react-native-storage#148]
一步步按照readme实现，使用global声明，然后如下：

        storage.save({
            key: 'user', 
            data: {
                id: 1,
                phoneNumber: '13399115522',
                password: '201511',
                gender: '男',
                age: 22
            },
        });

        storage.load({
            key: 'user'
        }).then(ret => {
            console.log('ret:' + user);
        }).catch(err => {
            console.warn(err.message);
            switch (err.name) {
            case 'NotFoundError':
                console.err('not found');
                break;
            case 'ExpiredError':
                console.err('expired');
                break;
            }
        });

但是控制台输出：
Can't find variable: user

请问这个是什么原因呢？

**Comment by sunnylqm** [comment]
```
.then(ret => {
        console.log('ret:' + user);
```
这里变量是ret，不是user啊

**Comment by sjmjulia** [comment]
zz了。多谢啊～
