### ISSUE TITLE
react-native环境，导入后初始化，之后打印storage,没有找到相关方法

### ISSUE THREAD

**Issue by wanchun0222** [sunnylqm/react-native-storage#15]
`var storage = new Storage({

  size: 10000,    

  //数据过期时间，默认一年（1000 * 3600 * 24 * 365 秒）
  defaultExpires: 1000 * 3600 * 24 * 365,

  //读写时在内存中缓存数据。默认启用。
  enableCache: true,

  sync : {
    //同步方法的具体说明会在后文提到
  }
});

console.log(storage);`

_SIZE:10000
_innerVersion:10
_m:Object
_mapPromise:Promise
_s:Object
cache:Object
defaultExpires:31536000000
enableCache:true
isPromise:true
sync:Object

以上是log的输出，并没有save、load等方法可用，请问我是使用有问题吗？谢谢……

**Comment by sunnylqm** [comment]
log输出的只是自身属性，babel对es6的class的语法转换，可能基于原型链方法实现，导致并不会在log中输出。__并不影响实际使用。__

**Comment by wanchun0222** [comment]
@sunnylqm  但是确实是用不了storage.load() storage.save() 方法，提示找不到该方法！

**Comment by sunnylqm** [comment]
贴一下具体代码和具体报错截图

**Comment by wanchun0222** [comment]
@sunnylqm 谢谢，已找到原因

**Comment by sunnylqm** [comment]
具体什么问题？

**Comment by wanchun0222** [comment]
@sunnylqm 你好，和你们的组件没有关系。 我在传storage到内页A时，在tab上是有3个按钮点击后传到同一内页A的（由于其它内页还没做好，所以都连接到了这个内页。）后面的2个按钮上的props上忘了加上这个storage了。所以后面的为空的值就覆盖了前面已经设置了值的，导致storage在内页为空了。

**Comment by sunnylqm** [comment]
没有必要把storage传来传去的，放在全局直接调用就很方便

**Comment by wanchun0222** [comment]
@sunnylqm 你好，谢谢你的回复。请教一下，如何放在全局？我是想在 添加页 多个列表页 及编辑页都能读取到保存的数据，如何放可以保证这些页面都能访问到数据而不用把storage传过去各页面去呢？谢谢……

**Comment by sunnylqm** [comment]
我在文档里面说了啊
![qq 20160505081438](https://cloud.githubusercontent.com/assets/615282/15033042/79285318-1299-11e6-9d62-db66dd81c49a.png)

**Comment by wanchun0222** [comment]
@sunnylqm 谢谢你的指点。祝好
