### ISSUE TITLE
catch问题

### ISSUE THREAD

**Issue by fangzongwu** [sunnylqm/react-native-storage#153]
**为什么storage.load()中捕捉不到catch()错误？**
storage.load({
			key: 'getToken',
		}).then((ret) => {
			console.log(ret);
		}).catch(err => {
			console.warn(err.message);
			switch (err.name) {
			    case 'NotFoundError':
			        // TODO;
			        break;
		        case 'ExpiredError':
		            // TODO
		            break;
			}
		})

**Comment by sunnylqm** [comment]
说具体

**Comment by fangzongwu** [comment]
就是这个getToken还没有存进去，我去load它，没有报错信息。这是哪里的问题？谢谢！

**Comment by sunnylqm** [comment]
说具体的意思是：
用的什么rn版本，什么storage版本，什么设备以及设备版本，是否调试模式，具体逻辑流程，预期结果，实际结果等等

**Comment by fangzongwu** [comment]
"react": "16.0.0",
"react-native": "0.48.4",
"react-native-storage": "^0.2.2",
设备：红米note2（MIUI 7.7.12），
调试模式，用户的信息保存在getToken中，通过判断这个信息是否存在，然后做进一步处理。
现在的情况是这个信息不存在时，load()方法没有执行catch(),没有报错信息，也没有执行console.log()
这是我的依赖(package.json)：
"dependencies": {
    "antd-mobile": "next",
    "antd-mobile-demo-data": "^0.1.4",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "cross-fetch": "^1.1.1",
    "es6-promise": "^4.1.1",
    "expo": "21.0.0",
    "mobx": "^3.3.1",
    "mobx-react": "^4.3.4",
    "react": "16.0.0",
    "react-dom": "16.0.0",
    "react-native": "0.48.4",
    "react-native-modal-dropdown": "^0.5.0",
    "react-native-qrcode": "^0.2.6",
    "react-native-storage": "^0.2.2",
    "react-navigation": "1.0.0-beta.11",
    "standard-error": "^1.1.0"
  }

**Comment by sunnylqm** [comment]
https://github.com/sunnylqm/react-native-storage/issues/147
