### ISSUE TITLE
storage.clearMap()不起作用

### ISSUE THREAD

**Issue by hongwei78** [sunnylqm/react-native-storage#155]
在iOS模拟器中logout时调用storage.clearMap();再次Ctrl+R重新加载页面，还是能用storage.load方法读出保存的key的value，clearMap并没有清除key-value。

**Comment by sunnylqm** [comment]
贴代码

**Comment by hongwei78** [comment]
let storage = new Storage({
  // 最大容量，默认值1000条数据循环存储
  size: 1000,
  // 存储引擎：对于RN使用AsyncStorage，对于web使用window.localStorage
  // 如果不指定则数据只会保存在内存中，重启后即丢失
  storageBackend: AsyncStorage,
  // 数据过期时间，默认一整天（1000 * 3600 * 24 毫秒），设为null则永不过期
  defaultExpires: null,
  // 读写时在内存中缓存数据。默认启用。
  enableCache: false,
  // 如果storage中没有相应数据，或数据已过期，
  // 则会调用相应的sync方法，无缝返回最新数据。
  // sync方法的具体说明会在后文提到
  // 你可以在构造函数这里就写好sync的方法
  // 或是在任何时候，直接对storage.sync进行赋值修改
  // 或是写到另一个文件里，这里require引入
  sync: {}
})
global.storage = storage;


=================================

    componentDidMount() {
      // 读取
      storage.load({
        key: 'loginState',
        // autoSync(默认为true)意味着在没有找到数据或数据过期时自动调用相应的sync方法
        autoSync: false,
        // syncInBackground(默认为true)意味着如果数据过期，
        // 在调用sync方法的同时先返回已经过期的数据。
        // 设置为false的话，则始终强制返回sync方法提供的最新数据(当然会需要更多等待时间)。
        syncInBackground: true
      }).then(ret => {
        // 如果找到数据，则在then方法中返回
        // 注意：这是异步返回的结果（不了解异步请自行搜索学习）
        // 你只能在then这个方法内继续处理ret数据
        // 而不能在then以外处理
        // 也没有办法“变成”同步返回
        // 你也可以使用“看似”同步的async/await语法

        console.log(ret.userid);
        this.setState({ user: ret });
        let url = global.server + "/CheckToken";
        let formData = new FormData();
        formData.append("userid",this.state.user.userid);
        formData.append("token",this.state.user.token);

        if(this.state.user.userid&&this.state.user.token){
          fetch(url , {
            method: 'POST',
            mode: "cors",
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              userid: this.state.user.userid,
              token: this.state.user.token,
            })
            //'userid='+this.state.user.userid+'&token='+this.state.user.token,
          }).then((response) => {
            return response.json();
          }).then((json) => {
            alert(JSON.stringify(json));
            if(json.code!=0){
              alert(json.msg);
              // !! 清除某个key下的所有数据
              storage.clearMapForKey('loginState');

              Actions.login();
            }
          }).catch((error) => {
            console.error(error);
          });
        }
        else{
          Actions.login();
        }
      }).catch(err => {
        //如果没有找到数据且没有sync方法，
        //或者有其他异常，则在catch中返回
        console.warn(err.message);
        switch (err.name) {
            case 'NotFoundError':
                // TODO;
                break;
            case 'ExpiredError':
                // TODO
                break;
        }
        Actions.login();
      })
      SplashScreen.hide()
    }


===============================

        <Button
          icon={{name: 'code'}}
          backgroundColor='#03A9F4'
          buttonStyle={{borderRadius: 0, marginLeft: 0, marginRight: 0, marginBottom: 0}}
          onPress={() => this.logout()}
          title='退出登录' />
      </Card>
      </View>
    );
  }
  logout = () =>{
      storage.clearMap();
      Actions.login();
  }

**Comment by sunnylqm** [comment]
文档中明确说明了：仅key-id数据
// !! 清除某个key下的所有数据(仅key-id数据)
storage.clearMapForKey('user');
