### ISSUE TITLE
Sometimes I cannot access storage if the app is reloaded

### ISSUE THREAD

**Issue by francisrod01** [sunnylqm/react-native-storage#159]
Sometimes I cannot access storage if the app is reloaded, so.. I need to compile the app again.
Why does it happen?

# Current Behavior

Sometime the app don't continues the steps after `LOAD_STORE_USER_DATA_REQUEST`, that the flag in redux-saga where the app reads the storage from the userdata.

![image](https://user-images.githubusercontent.com/4691768/36058301-ac3cc63c-0e03-11e8-85c7-50691ff2f69d.png)

# Expected Behavior

![image](https://user-images.githubusercontent.com/4691768/36057755-e5aad896-0df9-11e8-835e-754058dc2556.png)

**Comment by sunnylqm** [comment]
Maybe related to https://github.com/facebook/react-native/issues/14101

**Comment by sunnylqm** [comment]
Fixed in rn 0.57
