### ISSUE TITLE
new Storage()时所设置的defaultExpires，会对数据有什么影响？能否设为永久？

### ISSUE THREAD

**Issue by pampang** [sunnylqm/react-native-storage#16]
new Storage()时所设置的defaultExpires，会对数据有什么影响？能否设为永久？

**Comment by sunnylqm** [comment]
文档中都有说明：
1、设为null，则永不过期。
2、即便指定了且达到了过期时间，数据也不会被删除，而只是触发调用同步方法。

**Comment by pampang** [comment]
感谢你的回答！

`let storage = new Storage({
    //最大容量，默认值1000条数据循环存储
    size: 3000,

    //数据过期时间，默认一整天（1000 * 3600 * 24秒）
    defaultExpires: null,

    //读写时在内存中缓存数据。默认启用。
    enableCache: true,

    //如果storage中没有相应数据，或数据已过期，
    //则会调用相应的sync同步方法，无缝返回最新数据。
    sync: {
      //同步方法的具体说明会在后文提到
    }
  })`

在这样的情况下，storage.defaultExpires是864000，也就是默认值。

**Comment by pampang** [comment]
同时想请问一下：
```
storage.save({
    key: 'hello:world',
    // write sth...
})
```
如果key值中存在':'冒号等不能在函数名中出现的字符，在sync时会出错吗？如果我关闭sync，是否同样会出错呢？

**Comment by sunnylqm** [comment]
嗯，这里的默认值逻辑有点问题。不过不建议把这个全局默认过期时间设为永久吧，为什么会有这样的需求呢？

**Comment by sunnylqm** [comment]
key名需要和sync名相同，所以key的命令肯定也遵循函数命名的限制。不过如果你不触发sync，则应该不会出错。

**Comment by pampang** [comment]
好的，非常感谢！repo中的sync是非常有用的功能，可以帮助我们跳过非常的原本要写的逻辑。感谢~

**Comment by sunnylqm** [comment]
Enjoy!
