### ISSUE TITLE
Dose it has method clear all data like AsyncStorage.clear ?

### ISSUE THREAD

**Issue by GloriaCHL** [sunnylqm/react-native-storage#163]
你好，请问有清除全部数据的方法吗？类似于AsyncStorage.clear的。
我尝试过用AsyncStorage.clear来清除数据，但发现清除后，AsyncStorage.getItem 是没有数据了，但 storage.load 里依然可以拿到那条数据。
如果我想做清除全部数据的操作，不是一条条key去清除那种而是一次性全部数据清除，应该怎么做？

**Comment by sunnylqm** [comment]
文档看了吗

**Comment by GloriaCHL** [comment]
看了，只发现clearMap这个，但如果没有使用Id情况就不行了吧？

**Comment by sunnylqm** [comment]
有什么理由需要存了清清了存呢  无id的数据本意就是需要单独特别处理的  如果是批量处理的数据就应该走id

**Comment by GloriaCHL** [comment]
明白了，thanks

**Comment by GloriaCHL** [comment]
![default](https://user-images.githubusercontent.com/10557315/37143854-4a06281a-22f7-11e8-8cec-2ba11a9c3160.png)
![default](https://user-images.githubusercontent.com/10557315/37143961-a743ce7e-22f7-11e8-99d0-023d999e364c.png)
不好意思大佬，再请教一下clearMap的用法...
第一张截图是执行clearMap的函数代码，第二张截图是chrome的输出。可以看到执行clearMap代码后，那条数据依然还在，是我调用的写法有问题吗？还是？用在react-native里的，模拟器是MAC的默认模拟器。

**Comment by sunnylqm** [comment]
我看了下代码，clearMap目前缺乏返回值，在你这个场景没法用
建议用clearMapForKey接then或者await
不过很奇怪，我自己几乎没有碰到需要反复clear的场景啊？

**Comment by GloriaCHL** [comment]
![default](https://user-images.githubusercontent.com/10557315/37145724-91ba05fa-22fc-11e8-97aa-7ddbca5bb272.png)

都测试了下后，clearMapForKey有效。
clearMap执行后数据还在，刷新后没了。猜测是删了AsyncStorage里的，没删掉缓存里的。
反复clear只是我测试用而已，不是项目需求。因为在模拟器里又不能看到redux又不能看到storage的所以经常初始化所有数据来测试，所以就想有没有可以一次性全部清除的方法，就不用记那些key啊ID啊什么的了。

**Comment by sunnylqm** [comment]
不是没清缓存，而是因为异步。只是你不能马上连着去load，数据实际是清了
