### ISSUE TITLE
可以缓存视频文件吗

### ISSUE THREAD

**Issue by dream-approaching** [sunnylqm/react-native-storage#169]
稍微看了下，我的理解是这个库可以缓存一些字段数据之类的，可能看的还不是很透彻，我想问下这个可以实现断点续播吗

**Comment by sunnylqm** [comment]
只能存储可序列化(可转为字符串)的数据，且不建议存储大数据

断点续播跟存储没什么关系
那是视频编解码以及网络协议的事情

**Comment by dream-approaching** [comment]
好的，谢谢，我之后看到react-native-fetch-blob或许可以缓冲视频，正在测试，感谢你的回复
