### ISSUE TITLE
对于未save的key，直接通过load调用sync方法后，数据并不会存到storage中。

### ISSUE THREAD

**Issue by pampang** [sunnylqm/react-native-storage#17]
```
// storage.save({
      //   key: 'test',
      //   rawData: data,
      //   expires: null,
      // })
storage.load({
      key: 'test',
    }).then((data) => {
      // 将数据挂载到全局中
      this._provinces = data;
      console.log(storage);
    })
```
如果在load之前并没有save过任何关于key：test的数据，那么直接执行load方法后，打印出来的storage里面，依然不会存在key：test的任何数据。
这算是一个bug吗？

**Comment by InfinityBlue** [comment]
这个应该和之前是否save过key无关。
即使调用了sync方法，之后也需要你自己在resolve的时候调用save来保存到storage中。

sync只加载数据，并不会自己调用save。

不知道我是不是正确理解了你的问题

**Comment by pampang** [comment]
@InfinityBlue 这个理解是正确的。
但既然数据是按照我自己定义的模式来更新的，为什么不同时存储呢？
自己调用save，岂不是多了一步吗？

**Comment by sunnylqm** [comment]
接口返回的数据你是否要全部save，这个显然是不定的。所以并没有做自动的save。

**Comment by pampang** [comment]
@InfinityBlue  @sunnylqm  感谢两位！
