### ISSUE TITLE
Remove from table where id = ?

### ISSUE THREAD

**Issue by zippax** [sunnylqm/react-native-storage#177]
Thank you for the lib, I tried to use it on my project and I see that all function works fine when I want to insert, update, and read data.

also when I want to remove whole table it work fine with simple code: storage.remove('users')

my question is how to remove single item with id number. I tried the code in the document but it seems not work or maybe I didn't do it as it should be

my try : 

example to insert 4 records :

```
insert(){
    for (var i = 0; i < 5; i++) {
      storage.save({
      	key: 'users',   // Note: Do not use underscore("_") in key!
      	data: {
          id: i,
      		username: 'User # ' + i,
      	}
      });
    }
  }
```

example to delete from users table where id = 4

```
delete(){
    storage.remove({
    	key: 'users',
        id: 4
    })
  }
```

I hope I find a solution to fix that.

Thanks

**Comment by sunnylqm** [comment]
You did not use `id` in `save`(`id` is not part of `data`)

**Comment by zippax** [comment]
How do I use id in save ? I tried this and also doesn't work :
```
storage.save({
     key: 'users',
     id: 1, // Here I use both integer and string
     data: {
       username: 'User # 1',
     }
   });
```
