### ISSUE TITLE
为何重启APP后缓存数据才生效

### ISSUE THREAD

**Issue by gmars** [sunnylqm/react-native-storage#178]
用户登录后页面中是获取不到usertoken的需要重启APP才能获取到，求帮助
storages对象
let storages = new Storage({
  size: 1000,
  storageBackend: AsyncStorage,
  defaultExpires: null,
  enableCache: true,
});
设置及读取usertoken
/**
 * 获取用户登录信息
 */
storages.usertoken = storages.load({
  key: 'usertoken',
  id: '10002',
  autoSync: false,
  syncInBackground: true
})

/**
 * 设置用户登录token
 * @param token
 */
storages.setUserToken = (token) => {
  storages.save({
    key: 'usertoken',
    id: '10002',
    data: token
  })
}

**Comment by sunnylqm** [comment]
请仔细阅读文档，以及学习promise的用法
