### ISSUE TITLE
是否可以考虑同一文件的增量更新功能？

### ISSUE THREAD

**Issue by cj768025549** [sunnylqm/react-native-storage#181]
我目前想实现一个功能，把请求日志记录下来写在本地。但是发现如果每一个请求都记录一次的话，本地文件会非常多，想从其中排查有问题的日志会变得十分困难。是否可以考虑添加一个功能，将数据保存在一个文件里，每次增量更新，同时又不会覆盖？

**Comment by sunnylqm** [comment]
这个库只是对官方asyncstorage的封装，官方这个storage底层用什么，我不能决定，甚至官方自己也不会做出任何承诺（是否使用文件或是数据库）
日志这种功能，应该用专业的文件日志工具，无论是封装第三方还是自己写。storage应该用于少量业务数据，并不适合记录日志，它本身就不是为了方便你查看数据。
