### ISSUE TITLE
当使用key-id的方式取出数据的时候速度会比直接用key取出数据慢吗

### ISSUE THREAD

**Issue by NewStartMe** [sunnylqm/react-native-storage#185]
我发现当我用key-id的方式存储数据时，在我查询的时候，在手机上大概几百条数据就大概花费5秒钟时间，而当我直接用key-value 的方式存储数据，直接查询却花费很少时间，所以key-id的方式是不是底层在查询的时候也是先查出来这个key下的所有数据之后 然后查询出相应的id的数据？

**Comment by sunnylqm** [comment]
主要与查询次数有关
一次取出大量key-id是一条一条取的，500条就是500次。不过查询一次后就会缓存（缓存重启失效）

**Comment by NewStartMe** [comment]
如果我在这个key-id下存放了一个数组，而数组里有几百条 字符串数据，那查的时候是查一次呢还是查几百次呢？

**Comment by sunnylqm** [comment]
一个id一次

**Comment by NewStartMe** [comment]
好的 感谢解答
