### ISSUE TITLE
_reactNativeStorage.Storage is not a constructor  這是怎麼回事  直接複製demo 代碼的

### ISSUE THREAD

**Issue by GitHubHuan666** [sunnylqm/react-native-storage#187]
_reactNativeStorage.Storage is not a constructor
<unknown>
    C:\Users\014347\LGZAPP\index.js:17:14
loadModuleImplementation
    C:\Users\014347\LGZAPP\node_modules\metro\src\lib\polyfills\require.js:214:4
guardedLoadModule
    C:\Users\014347\LGZAPP\node_modules\metro\src\lib\polyfills\require.js:141:20
_require
    C:\Users\014347\LGZAPP\node_modules\metro\src\lib\polyfills\require.js:132:2
<unknown>
    
executeApplicationScript
    debuggerWorker.js:38:9
<unknown>
    debuggerWorker.js:63:7

**Comment by sunnylqm** [comment]
你代码肯定不对

**Comment by GitHubHuan666** [comment]
@sunnylqm   import { AsyncStorage,AppRegistry,Text,Button,View,WebView,StyleSheet,Dimensions } from 'react-native';
import React, { Component } from 'react';
import {Storage} from 'react-native-storage';
import {TabNavigator,createStackNavigator,StackNavigator,createBottomTabNavigator } from 'react-navigation';
import Home from './src/Home';
import TAOBAOILOTINBOX from './src/taobao/TAOBAOILOTINBOX';
import Sharelist from './src/Sharelist';
import login from './src/login';
我加了下面這段就報錯了, 不是這樣寫嗎?
var storage = new Storage({
    // 最大容量，默认值1000条数据循环存储
    size: 1000,
    // 存储引擎：对于RN使用AsyncStorage，对于web使用window.localStorage
    // 如果不指定则数据只会保存在内存中，重启后即丢失
    storageBackend: AsyncStorage,
    // 数据过期时间，默认一整天（1000 * 3600 * 24 毫秒），设为null则永不过期
    defaultExpires: 1000 * 3600 * 24,
    // 读写时在内存中缓存数据。默认启用。
    enableCache: true,
    // 如果storage中没有相应数据，或数据已过期，
    // 则会调用相应的sync方法，无缝返回最新数据。
    // sync方法的具体说明会在后文提到
    // 你可以在构造函数这里就写好sync的方法
    // 或是在任何时候，直接对storage.sync进行赋值修改
    // 或是写到另一个文件里，这里require引入
    // sync: require('你可以另外写一个文件专门处理sync')   
  })  
  global.storage = storage;

**Comment by GitHubHuan666** [comment]
@sunnylqm  我找到錯誤了.... 是我粗心  引入的時候 加了花括號!!! 習慣性...
