### ISSUE TITLE
如何与redux 配合使用

### ISSUE THREAD

**Issue by Slebee** [sunnylqm/react-native-storage#19]
react native + redux，如果我需要把数据存储在storage里，然后每次重新打开app的时候redux的store都读取storage中的数据，该如何实现，AsyncStorage是异步的导致没法在一开始初始化store的时候就读取到storage的数据，请问该怎么做比较好

**Comment by sunnylqm** [comment]
我不太了解redux。。。

**Comment by Slebee** [comment]
留下解决方案，只要在加载redux开始之前使用就好了，当读取完数据之后再利用一个加载的页面来触发redux启动，将获取到的数据传入redux，分配给各个需要的reducers 的初始state即可
