### ISSUE TITLE
English grammar mistakes in readme.md

### ISSUE THREAD

**Issue by pashute** [sunnylqm/react-native-storage#192]
I wish to correct the many mistakes in the readme.md  
 
Examples:  

`...don't have to do anything(but require`...  -- missing space and should read:
 `...do not have to do anything,  (but version >= 0.13 is required`

    // Use AsyncStorage for RN, or window.localStorage for web.
    // If not set, data would be lost after reload.
    storageBackend: AsyncStorage,

Should be: 

    // Storage Back-End:  For RN use AsyncStorage, for a React web app use window.localStorage.
    // If storageBackend is not set, the data will be lost after a reload
    * storageBackend: AsyncStorage, 

and many more...

Could you add me to the team so I can edit it, or propose some other way?

**Comment by sunnylqm** [comment]
![edit](https://user-images.githubusercontent.com/615282/44965228-15617180-af67-11e8-9282-ed1ddcc186db.png)

**Comment by pashute** [comment]
somehow that disapeared
