### ISSUE TITLE
Unexpected use of reserved word 'export'

### ISSUE THREAD

**Issue by eljago** [sunnylqm/react-native-storage#2]
Hello, I tried to use this library but I'm getting an error on launch: SyntaxError: Unexpexted use of reserved word 'export' 

![image](https://cloud.githubusercontent.com/assets/2080977/9697379/ea1b9b0e-5361-11e5-846d-10c839240f29.png)

I'm new to react-native. Am I missing an installation step?

**Comment by sunnylqm** [comment]
Sorry for missing step in readme.
You need to modify node_modules/react-native/packager/transformer.js ,
add a 'es6.modules', line to the whitelist.
I'll fix this to fit the default options later.

**Comment by sunnylqm** [comment]
Or put this babel config file under your project directory
https://github.com/brentvatne/react-native-animated-demo-tinder/blob/master/.babelrc

**Comment by eljago** [comment]
It worked using the .babelrc file. Thanks!!
