### ISSUE TITLE
Initializing new storage

### ISSUE THREAD

**Issue by hungngo97** [sunnylqm/react-native-storage#208]
I'm having trouble with reloading the data when I open the app again ( I did save the data before), but the data is lost after I restart the app. How should I set the storageBackend to prevent this? Thanks for great library.  

// Use AsyncStorage for RN apps, or window.localStorage for web apps.
  // If storageBackend is not set, data will be lost after reload.
  storageBackend: AsyncStorage, // for web: window.localStorage

**Comment by hungngo97** [comment]
In detail, I saved data during usage of the app and want that data to remain, but when I restart the app, the default data of autosync method keeps override my data.

**Comment by sunnylqm** [comment]
Post your code here

**Comment by hungngovinh** [comment]
Hey I am sorry for the late response :) apparently when I initializing the memory I accidentally put the memory removal at the end of the app file for testing so it gets deleted whenever my App is up. Thanks for the great library
