### ISSUE TITLE
data missing

### ISSUE THREAD

**Issue by githubxun** [sunnylqm/react-native-storage#21]
sometimes !!! on v1.0.6 the data is missing, when i killed the thread directly

**Comment by sunnylqm** [comment]
I don't quite get your point.

**Comment by githubxun** [comment]
I use it to store some of my account information, but when I exit directly above the ios or android application, sometimes there will be a loss of data. data is null

**Comment by sunnylqm** [comment]
Well, if that is true, I can do nothing with this problem. You may open an issue on offical RN asyncstorage API.

**Comment by sunnylqm** [comment]
Or if you find different results between the raw asyncstorage API and react-native-storage, reopen this and post some codes here. Thanks.

**Comment by helloeyesimple** [comment]
I'm getting this issue also, despite using the following version:

"react-native": "0.52.0",
"react": "16.2.0",
"react-native-storage": "^0.2.2",

Here's the config:

storage: new Storage({
          // maximum capacity, default 1000
          size: 1000000000,

          // Use AsyncStorage for RN, or window.localStorage for web.
          // If not set, data would be lost after reload.
          storageBackend: AsyncStorage,

          // expire time, default 1 day(1000 * 3600 * 24 milliseconds).
          // can be null, which means never expire.
          // defaultExpires: 1000 * 3600 * 24,
          defaultExpires: null,

          // cache data in the memory. default is true.
          enableCache: true,

          // if data was not found in storage or expired,
          // the corresponding sync method will be invoked and return
          // the latest data.
          sync : {
              // we'll talk about the details later.
          }
      }),


This issue sometimes happening if the user kill the app using clear cache icon. Might it be happening because "enableCache" is true?
