### ISSUE TITLE
Network request failed

### ISSUE THREAD

**Issue by CrisChr** [sunnylqm/react-native-storage#212]
autoSync设置为true，key为‘movie’，当执行storage.sync函数时警告“Network request failed”，api经验证有效
```
componentDidMount() {
    const { state: { params: { id } } } = this.props.navigation
    console.log('id: ', id)
    const result = storage.load({
      key: 'movie',
      id: id,
      autoSync: true,
      syncInBackground: true,
      syncParams: {
        movieId: id
      }
    }).then((ret) => {
      return ret;
    }).catch(err => {
      console.warn(err.message)
      switch (err.name) {
        case 'NotFoundError':
          break;

        case 'ExpiredError':
          break;
      }
    })

    console.log('result: ', result)
    const that = this
    storage.sync = {
      async movie(params) {
        const {
          syncParams: {
            movieId
          }
        } = params
        console.log('movie id: ', movieId)
        console.log('api: ', `${that.api}/${movieId}`)
        const rawResponse = await fetch(`${this.api}/${movieId}`)
        const textResponse = await rawResponse.text()
        const jsonResponse = JSON.parse(textResponse)
        console.log('json: ', jsonResponse)
        if (jsonResponse) {
          that.setState({
            data: jsonResponse,
            ready: true
          })
          storage.save({
            key: 'movie',
            id: movieId,
            data: jsonResponse
          })
        }
      }
    }
  }
```
![image](https://user-images.githubusercontent.com/38416380/52898316-2ea96200-3217-11e9-84cb-fc6e857e3a65.png)
![image](https://user-images.githubusercontent.com/38416380/52898326-4385f580-3217-11e9-8753-948133b396af.png)

**Comment by sunnylqm** [comment]
console.log('api: ', `${that.api}/${movieId}`)
        const rawResponse = await fetch(`${this.api}/${movieId}`)

一个this一个that并不一致啊

这个代码逻辑也很奇怪，为啥要把sync写到组件里面？而且为啥要在sync时候setState？

**Comment by CrisChr** [comment]
谢谢
对于this和that，确实时马虎了，没有注意到，抱歉
对于sync，我本来的想法是当组件挂载完成后（did mount），如果本地没有数据缓存就执行storage.sync函数从远程获取，然后更新状态

**Comment by CrisChr** [comment]
又仔细阅读了下文档，调试成功
原因：由于storage.load是异步的，只能在then函数里处理返回的ret，如果抛出异常，即Not found或Expired，则会无缝返回storage.sync
`api = 'https://api.douban.com/v2/movie/subject'

  componentDidMount() {
    const {
      state: {
        params: {
          id
        }
      }
    } = this.props.navigation
    console.log('id: ', id)
    storage.load({
      key: 'movie',
      id: id,
      autoSync: true,
      syncInBackground: true,
      syncParams: {
        movieId: id
      }
    }).then((ret) => {
      this.setState({
        data: ret,
        ready: true
      })
    }).catch(err => {
      console.warn(err.message)
      switch (err.name) {
        case 'NotFoundError':
          break;

        case 'ExpiredError':
          break;
      }
    })

    const that = this
    storage.sync = {
      async movie(params) {
        const {
          syncParams: {
            movieId
          }
        } = params
        const rawResponse = await fetch(`${that.api}/${movieId}`)
        const textResponse = await rawResponse.text()
        const jsonResponse = JSON.parse(textResponse)
        console.log('json: ', jsonResponse)
        if (jsonResponse) {
          storage.save({
            key: 'movie',
            id: movieId,
            data: jsonResponse
          })
          return jsonResponse
        }
      }
    }
  }`
