### ISSUE TITLE
为什么看不见原生代码？

### ISSUE THREAD

**Issue by CocoaZX** [sunnylqm/react-native-storage#215]
使用没有问题。有一个疑问
之前使用的插件都是可以直接看见原生代码的，为什么这个看不见原生代码。
而npm install 之后在项目里有原生代码。

**Comment by sunnylqm** [comment]
因为本来就没有原生代码

**Comment by CocoaZX** [comment]
看到了，pagejson里面依赖的有。生成的json文件肯定还是需要原生创建文件来保存
