### ISSUE TITLE
How to use syncInBackground correctly

### ISSUE THREAD

**Issue by liganghui** [sunnylqm/react-native-storage#218]
I want to realize that when the data expires, I get the expired data first, and then get the new data returned by Sync method. But in fact, I can only get the expired data. The new data is stored, but not returned. What did I do wrong?

Demo 
![QQ截图20190401160953](https://user-images.githubusercontent.com/15844198/55313751-26417980-549b-11e9-9805-11c3df3547dc.png)
![QQ截图20190401160942](https://user-images.githubusercontent.com/15844198/55313753-2772a680-549b-11e9-8303-9f4e7da29a88.png)
![QQ截图20190401160930](https://user-images.githubusercontent.com/15844198/55313755-28a3d380-549b-11e9-82e1-d4de92588526.png)

**Comment by sunnylqm** [comment]
You can get only one of them at one time.

**Comment by liganghui** [comment]
ok  , so  you can close this.
