### ISSUE TITLE
初次调用storage.load().then()不会有数据返回，要第二次以上才有数据。

### ISSUE THREAD

**Issue by LeeZC** [sunnylqm/react-native-storage#222]
相关设置：
sync:require('./NetWorkSync'),

调用如下：
`
global.storage.load({
            key: key,
            id: saveId,
            autoSync: true,
            syncInBackground: true,
            syncParams: {
                extraFetchOptions: {
                    // 各种参数
                    pageNumber:pageNumber,
                    saveId:saveId,
                },
                someFlag: true,
            },
        }).then(ret => {

            this.setState({
                dataObj:ret,
            });

        }).catch(err => {
            console.warn(err.message);
            switch (err.name) {
                case 'NotFoundError':
                    // TODO;
                    break;
                case 'ExpiredError':
                    // TODO
                    break;
            }
        });
    };
`

NetWorkSync.js 文件内实现如下：
`
function follow(params) {

    let { id, resolve, reject, syncParams: { extraFetchOptions, someFlag } } = params;

    let pageNumber=extraFetchOptions.pageNumber;
    let saveId=extraFetchOptions.saveId;
    let aparams={
        page:pageNumber,
    };

    RNFetchBlob.fetch('POST', requesturl, {
        Authorization : "Bearer access-token",
        otherHeader : "",
        'Content-Type' : 'multipart/form-data',
    }, [
        { name : 'params', data : JSON.stringify(aparams)},
        {name:'uid',data:uid},
        {name:'ctl',data:ctl},
        {name:'act',data:act},

    ]).then((resp) => {
        let respondData=resp.json();
        if(respondData && respondData.data){

            storage.save({
                key: 'follow',
                id: saveId,
                data: respondData.data
            });

            if (someFlag) {
                // 根据syncParams中的额外参数做对应处理
            }
            // 成功则调用resolve
            resolve && resolve(respondData.data);
        }
        else{
            // 失败则调用reject
            reject && reject(new Error('data parse error'));
        }

    }).catch((err) => {
        console.warn(err);
        reject && reject(err);
    })
}
`
第一次调用，虽然触发了follow方法请求数据，但是数据下载完成后，并没有返回到load方法then()的位置。第二次及以上load才有数据返回。 我在follow方法里打了断点，resolve和reject 都是undefined，是否是这个这个原因？请指教，不知道如何让请求数据完成后无缝返回到load.then()方法里边，

**Comment by sunnylqm** [comment]
什么版本？1.0的sync写法已经变了Sent from my Huawei phone-------- Original Message --------Subject: [sunnylqm/react-native-storage] 初次调用storage.load().then()不会有数据返回，要第二次以上才有数据。 (#222)From: LeeZC To: sunnylqm/react-native-storage CC: Subscribed 相关设置：

sync:require('./NetWorkSync'),

调用如下：

`global.storage.load({

key: key,

id: saveId,

autoSync: true,

syncInBackground: true,

syncParams: {

extraFetchOptions: {

// 各种参数

pageNumber:pageNumber,

saveId:saveId,

},

someFlag: true,

},

}).then(ret => {

        this.setState({

            dataObj:ret,

        });



    }).catch(err => {

        console.warn(err.message);

        switch (err.name) {

            case 'NotFoundError':

                // TODO;

                break;

            case 'ExpiredError':

                // TODO

                break;

        }

    });

};`



NetWorkSync.js 文件内实现如下：

`

function follow(params) {

let { id, resolve, reject, syncParams: { extraFetchOptions, someFlag } } = params;



let pageNumber=extraFetchOptions.pageNumber;

let saveId=extraFetchOptions.saveId;

let aparams={

    page:pageNumber,

};



RNFetchBlob.fetch('POST', requesturl, {

    Authorization : "Bearer access-token",

    otherHeader : "",

    'Content-Type' : 'multipart/form-data',

}, [

    { name : 'params', data : JSON.stringify(aparams)},

    {name:'uid',data:uid},

    {name:'ctl',data:ctl},

    {name:'act',data:act},



]).then((resp) => {

    let respondData=resp.json();

    if(respondData && respondData.data){



        storage.save({

            key: 'follow',

            id: saveId,

            data: respondData.data

        });



        if (someFlag) {

            // 根据syncParams中的额外参数做对应处理

        }

        // 成功则调用resolve

        resolve && resolve(respondData.data);

    }

    else{

        // 失败则调用reject

        reject && reject(new Error('data parse error'));

    }



}).catch((err) => {

    console.warn(err);

    reject && reject(err);

})



}

`

第一次调用，虽然触发了follow方法请求数据，但是数据下载完成后，并没有返回到load方法then()的位置。第二次及以上load才有数据返回。 我在follow方法里打了断点，resolve和reject 都是undefined，是否是这个这个原因？请指教，不知道如何让请求数据完成后无缝返回到load.then()方法里边，

**Comment by LeeZC** [comment]
> 什么版本？1.0的sync写法已经变了Sent from my Huawei phone-------- Original Message --------Subject: [sunnylqm/react-native-storage] 初次调用storage.load().then()不会有数据返回，要第二次以上才有数据。 (#222)From: LeeZC To: sunnylqm/react-native-storage CC: Subscribed 相关设置： sync:require('./NetWorkSync'), 调用如下： `global.storage.load({ key: key, id: saveId, autoSync: true, syncInBackground: true, syncParams: { extraFetchOptions: { // 各种参数 pageNumber:pageNumber, saveId:saveId, }, someFlag: true, }, }).then(ret => { this.setState({ dataObj:ret, }); }).catch(err => { console.warn(err.message); switch (err.name) { case 'NotFoundError': // TODO; break; case 'ExpiredError': // TODO break; } }); };` NetWorkSync.js 文件内实现如下： ` function follow(params) { let { id, resolve, reject, syncParams: { extraFetchOptions, someFlag } } = params; let pageNumber=extraFetchOptions.pageNumber; let saveId=extraFetchOptions.saveId; let aparams={ page:pageNumber, }; RNFetchBlob.fetch('POST', requesturl, { Authorization : "Bearer access-token", otherHeader : "", 'Content-Type' : 'multipart/form-data', }, [ { name : 'params', data : JSON.stringify(aparams)}, {name:'uid',data:uid}, {name:'ctl',data:ctl}, {name:'act',data:act}, ]).then((resp) => { let respondData=resp.json(); if(respondData && respondData.data){ storage.save({ key: 'follow', id: saveId, data: respondData.data }); if (someFlag) { // 根据syncParams中的额外参数做对应处理 } // 成功则调用resolve resolve && resolve(respondData.data); } else{ // 失败则调用reject reject && reject(new Error('data parse error')); } }).catch((err) => { console.warn(err); reject && reject(err); }) } ` 第一次调用，虽然触发了follow方法请求数据，但是数据下载完成后，并没有返回到load方法then()的位置。第二次及以上load才有数据返回。 我在follow方法里打了断点，resolve和reject 都是undefined，是否是这个这个原因？请指教，不知道如何让请求数据完成后无缝返回到load.then()方法里边， —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

 "react-native": "^0.58.6",
"react-native-storage": "^1.0.0-beta.1",

**Comment by LeeZC** [comment]
> 什么版本？1.0的sync写法已经变了Sent from my Huawei phone-------- Original Message --------Subject: [sunnylqm/react-native-storage] 初次调用storage.load().then()不会有数据返回，要第二次以上才有数据。 (#222)From: LeeZC To: sunnylqm/react-native-storage CC: Subscribed 相关设置： sync:require('./NetWorkSync'), 调用如下： `global.storage.load({ key: key, id: saveId, autoSync: true, syncInBackground: true, syncParams: { extraFetchOptions: { // 各种参数 pageNumber:pageNumber, saveId:saveId, }, someFlag: true, }, }).then(ret => { this.setState({ dataObj:ret, }); }).catch(err => { console.warn(err.message); switch (err.name) { case 'NotFoundError': // TODO; break; case 'ExpiredError': // TODO break; } }); };` NetWorkSync.js 文件内实现如下： ` function follow(params) { let { id, resolve, reject, syncParams: { extraFetchOptions, someFlag } } = params; let pageNumber=extraFetchOptions.pageNumber; let saveId=extraFetchOptions.saveId; let aparams={ page:pageNumber, }; RNFetchBlob.fetch('POST', requesturl, { Authorization : "Bearer access-token", otherHeader : "", 'Content-Type' : 'multipart/form-data', }, [ { name : 'params', data : JSON.stringify(aparams)}, {name:'uid',data:uid}, {name:'ctl',data:ctl}, {name:'act',data:act}, ]).then((resp) => { let respondData=resp.json(); if(respondData && respondData.data){ storage.save({ key: 'follow', id: saveId, data: respondData.data }); if (someFlag) { // 根据syncParams中的额外参数做对应处理 } // 成功则调用resolve resolve && resolve(respondData.data); } else{ // 失败则调用reject reject && reject(new Error('data parse error')); } }).catch((err) => { console.warn(err); reject && reject(err); }) } ` 第一次调用，虽然触发了follow方法请求数据，但是数据下载完成后，并没有返回到load方法then()的位置。第二次及以上load才有数据返回。 我在follow方法里打了断点，resolve和reject 都是undefined，是否是这个这个原因？请指教，不知道如何让请求数据完成后无缝返回到load.then()方法里边， —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

哦哦，如果我的写法不对的话，请问可否指教一个示例，文档里边那个写法不太明白，

**Comment by sunnylqm** [comment]
文档里就是一个示例啊，我不清楚你具体哪里不明白？

**Comment by liganghui** [comment]
I think I know the problem you have encountered and I solved it.
I determine the latest data or load the cache by judging the network environment.
But doing so increases the load time when there is a network.

Chinese :
```
  我想我知道你的问题 , 我是这样解决的.通过网络环境来判断加载缓存还是调用最新的数据，但是这样做会增加有网络时的数据加载时间。
```

if you react-native>=0.59
```js
yarn add @react-native-community/netinfo
react-native link @react-native-community/netinfo
```

index.js
```js
import NetInfo from  "react-native"; //RN<=0.58
import NetInfo from "@react-native-community/netinfo; //RN>=0.59
  
  NetInfo.getConnectionInfo().then(connectionInfo => {
      let type = connectionInfo.type == ("wifi" || "cellular") ? false : true;
      storage
        .load({ key: "xxxx",syncInBackground: type })
        .then(responseJson => {
          // do sth....
        })
        .catch(error => {
          console.warn(error);
        });
    });   
```
sync.js

```js
 .....

 xxxx(params) {
    let {id} = params;
    return Fetch.get('http://.....').then(json => {
        if (json) {
            global.storage.save({
                    key: 'xxxx',
                    id,
                    data: json,
                });
                return json
            } else {
                return null
        }
    }).catch(err => {
            return Promise.reject(err);
    });
 }
```

**Comment by LeeZC** [comment]
> I think I know the problem you have encountered and I solved it.
> I determine the latest data or load the cache by judging the network environment.
> But doing so increases the load time when there is a network.
> 
> Chinese :
> 我想我知道你的问题 , 我是这样解决的.通过网络环境来判断加载缓存还是调用最新的数据，但是这样做会增加有网络时的数据加载时间。
> 
> if you react-native>=0.59
> 
> ```js
> yarn add @react-native-community/netinfo
> react-native link @react-native-community/netinfo
> ```
> 
> index.js
> 
> ```js
> import NetInfo from  "react-native"; //RN<=0.58
> import NetInfo from "@react-native-community/netinfo"; //RN>=0.59
>   
>   NetInfo.getConnectionInfo().then(connectionInfo => {
>       let type = connectionInfo.type == ("wifi" || "cellular") ? false : true;
>       storage
>         .load({ key: "xxxx",syncInBackground: type })
>         .then(responseJson => {
>           // do sth....
>         })
>         .catch(error => {
>           console.warn(error);
>         });
>     });   
> ```
> 
> sync.js
> 
> ```js
>  .....
> 
>  xxxx(params) {
>     return Fetch.get('http://.....').then(json => {
>         if (json) {
>             global.storage.save({
>                     key: 'xxxx',
>                     data: json,
>                 });
>                 return json
>             } else {
>                 return null
>         }
>     }).catch(err => {
>             return Promise.reject(err);
>     });
>  }
> ```

多谢你的回答，我这里遇到的问题主要是在没有缓存的情况下调用storage.load，网络数据请求下来，没有回调返回数据，按照作者的回答，是因为我是最新的react-native-storage版本，sync写法过时了，我现在暂时还没有修改，到时候我打算按照新的写法改一下，或者降到老版本。

**Comment by LeeZC** [comment]
> 文档里就是一个示例啊，我不清楚你具体哪里不明白？

你好，我按照文档里的实例改写了，但是现象还是一样的，初次调用一个sync方法返回的数据是undefined，当这个方法请求数据完成后，并没有再把数据回调给storage.load。sync方法如下：
`async rank(params) {

        let { id, resolve, reject, syncParams: { extraFetchOptions, someFlag } } = params;

        let pageNumber=extraFetchOptions.pageNumber;
        let saveId=extraFetchOptions.saveId;

        RNFetchBlob.fetch('POST', requesturl, {
            Authorization : "Bearer access-token",
            otherHeader : "",
            'Content-Type' : 'multipart/form-data',
        }, [
            { name : 'params', data : JSON.stringify(aparams)},
            {name:'ctl',data:ctl},
            {name:'act',data:act},

        ]).then((resp) => {
            let respondData=resp.json();
            if(respondData && respondData.data){
                storage.save({
                    key: 'rank',
                    id: saveId,
                    data: respondData.data,
                    //expires: 1000 * 60 * 5,
                });
                return respondData.data;
            }
        }).catch((err) => {
            console.warn(err);
            //reject && reject(err);
            return err;
        })
    }`

会不会是我的设置有问题？
`global.storage.load({

            key: key,
            id: saveId,
            // autoSync(默认为true)意味着在没有找到数据或数据过期时自动调用相应的sync方法
            autoSync: true,
            // syncInBackground(默认为true)意味着如果数据过期，
            // 在调用sync方法的同时先返回已经过期的数据。
            // 设置为false的话，则等待sync方法提供的最新数据(当然会需要更多时间)。
            syncInBackground: true,
            // 你还可以给sync方法传递额外的参数
            syncParams: {
                extraFetchOptions: {
                    // 各种参数
                    pageNumber:pageNumber,
                    type:this.state.currentSelectType,
                    uid:global.storage.uid,
                    saveId:saveId,
                },
                someFlag: true,
            },
        })`

**Comment by LeeZC** [comment]
> RNFetchBlob.fetch

我明白我的问题出在哪儿了， 是sync里边，我用的是RNFetchBlob.fetch，这个请求本身就是异步的，
