### ISSUE TITLE
if the data is expired, wether the data will auto be cleared ?

### ISSUE THREAD

**Issue by ceerqingting** [sunnylqm/react-native-storage#223]
storage.save({
  key: 'loginState', // Note: Do not use underscore("_") in key!
  data: {
    from: 'some other site',
    userid: 'some userid',
    token: 'some token'
  },

  // if expired, the loginState will be clear or still exit in storage?
  expires: 1000 * 3600
});

**Comment by ceerqingting** [comment]
from the source code ,it won't

**Comment by sunnylqm** [comment]
Won't be cleared. Just trigger sync method or throw expired error.
