### ISSUE TITLE
如何设置才能不触发async网络请求，

### ISSUE THREAD

**Issue by LeeZC** [sunnylqm/react-native-storage#225]
App里判断如果设置了抓包代理，这个时候我就不触发请求数据的async方法，而只是加载以及缓存的数据，请问有设置不触发async网络请求的开关吗，

**Comment by sunnylqm** [comment]
比如可以这样咯
```
sync: 是否设置了代理 ? {} : syncModules
```

**Comment by LeeZC** [comment]
> 比如可以这样咯
> 
> ```
> sync: 是否设置了代理 ? {} : syncModules
> ```

我的意思是能不能在调用global.storage.load 的时候，有一个bool参数设定是否触发async方法，

**Comment by sunnylqm** [comment]
你也可以在sync方法里去判断啊

**Comment by LeeZC** [comment]
> 你也可以在sync方法里去判断啊

只能这么做了。。。
