### ISSUE TITLE
ios原生使用RN,报错[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

### ISSUE THREAD

**Issue by hms111111** [sunnylqm/react-native-storage#226]
已经pod了,react-native link @react-native-community/async-storage没反应,不知道要怎么弄?

**Comment by cizhaoyang** [comment]
我的也是这个错误 你的弄好了吗

**Comment by domingowensnsoft** [comment]
plz watch doc in @react-native-community/async-storage, maybe use manual setting by yourself

**Comment by nobodyhi** [comment]
同问有人解决吗？
931728085 QQ 号，求分享。

**Comment by sunnylqm** [comment]
请去相应repo里提问
