### ISSUE TITLE
Unable to resolve "./error" from "node_modules/react-native-web-storage/distribution/storage.js"

### ISSUE THREAD

**Issue by DoresP** [sunnylqm/react-native-storage#227]
Hi!
error.js seems to sit outside of the "distribution" folder so require('./error') doesn't work.
When changed to '../error' it works.

P.S. Thanks for your contribution to the react-native-web community :)

**Comment by sunnylqm** [comment]
Wrong repo? https://github.com/aurity/react-native-web-storage

**Comment by DoresP** [comment]
Yup! Sorry!
