### ISSUE TITLE
Q - can it access local storage data created by another app?

### ISSUE THREAD

**Issue by vovkind** [sunnylqm/react-native-storage#228]
Hi.

I'm working on a new generation of some mobile app (prev version written in Cordova and using local storage). I need to migrate user data, means copy existing data from local storage upon launch of the new version to the RN async storage.

By using storage.getBatchData I'm not able to access data in local storage(like just no data exist). Some ideas to solve the issue?

**** Configuration**********
const storage = new Storage({
    size: 1000,

    // Please note, I'm runinng the flow from RN app, but want access local storage
    storageBackend: window.localStorage,

    defaultExpires: null,

    enableCache: true,
  });

//Accessing...
storage.getBatchData(keysArr)
    .then((results) => {...}
....

**Thank you, guys!**

**Comment by sunnylqm** [comment]
The only way for you to migrate I think  is to load your legacy data in your legacy app and upload to the server.
The localstorage can only be accessed by the exact same webview in the exact same app.
