### ISSUE TITLE
expires的作用

### ISSUE THREAD

**Issue by ds-aco** [sunnylqm/react-native-storage#23]
expires: 30000  
defaultExpires: 1000 * 30,
将时间设置成这个   但是数据一直在
过期时间的意思是什么？

**Comment by ds-aco** [comment]
```
storage.save({
		    key: 'loginState', 
		    rawData: { 
		      from: 'some other site',
		      userid: 'some userid',
		      token: 'some token'
		    },
		    expires: 30000
		});
```
i expect 3minutes later the data is undefined ,but the data is always there,i can load the data anytime

**Comment by sunnylqm** [comment]
如果你用的是0.1.0之前的版本，那么对于key-only的数据来说，确实没有真正意义的过期。过期后会触发同名sync函数（如果存在），如果不存在，则仍然返回过期的数据。
0.1.0的版本开始，如果没有同名sync函数，则会触发catch。另外  30000表示的是30秒，而不是3分钟

**Comment by ds-aco** [comment]
我用的是 0.1.0
就是说 如果不执行remove操作 这个数据不会消失,一直存在
设置过期时间为一天,一天之后如果取数据,它会调用sync函数取数据
我这么理解对吗？

**Comment by sunnylqm** [comment]
对，但一天之后如果没有sync函数，是取不出来数据的，只会触发catch（应该是这样，如果不对，请告知我，我看下是不是bug

**Comment by ds-aco** [comment]
我试试看,如果有问题我会告诉你
谢谢你的答复
