### ISSUE TITLE
load没回调then, 没有数据返回

### ISSUE THREAD

**Issue by phomel** [sunnylqm/react-native-storage#230]
react 0.59.0

**Comment by phomel** [comment]
重启或者翻墙又可以了  没找到问题

**Comment by phomel** [comment]
@sunnylqm 会有这个问题么 .  我魅族  经常这个回调不回来

**Comment by sunnylqm** [comment]
0.57版本前的rn有这个问题 https://github.com/sunnylqm/react-native-storage/issues/147

**Comment by phomel** [comment]
我是0.59的版本

**Comment by sunnylqm** [comment]
嗯，一直都有线程被其他原生模块阻塞的可能，https://github.com/react-native-community/async-storage/blob/LEGACY/docs/advanced/DedicatedExecutor.md

**Comment by phomel** [comment]
加这个AsyncStorage_dedicatedExecutor=true的作用是什么, 有点没看懂,   加了 , 但还是没什么用. . .有些手机好像不会这样

**Comment by sunnylqm** [comment]
作用就是使用独立的线程，避免被阻塞

**Comment by phomel** [comment]
升级后重新打包后可以了  谢谢

**Comment by jun58** [comment]
我想问一下，在debugger模式下有用吗？我配置了但是还是不生效，刚设置之后是可以获取到的。重启app之后就获取不到了
**这是刚设置的时候：**
![image](https://user-images.githubusercontent.com/20509429/65496851-d2fd3080-deeb-11e9-92a0-1e572f9685bd.png)
![image](https://user-images.githubusercontent.com/20509429/65496893-e4463d00-deeb-11e9-8c53-0e892b601ad0.png)
**这是重启之后的：**
![image](https://user-images.githubusercontent.com/20509429/65496941-f88a3a00-deeb-11e9-889c-706c63451658.png)
![image](https://user-images.githubusercontent.com/20509429/65497009-12c41800-deec-11e9-9ef0-f3e53ae38a22.png)
**这个是配置：**
![image](https://user-images.githubusercontent.com/20509429/65497086-2c655f80-deec-11e9-8056-7cb1364745e1.png)
**这个是版本：**

**Comment by sunnylqm** [comment]
@jun58 上面说的是then和catch都不触发的情况，但你这个有catch触发，你有指定storageBackend吗

**Comment by jun58** [comment]
> @jun58 上面说的是then和catch都不触发的情况，但你这个有catch触发，你有指定storageBackend吗

是这样吗？
![image](https://user-images.githubusercontent.com/20509429/65497437-d80eaf80-deec-11e9-8119-c1253c2a3835.png)

**Comment by jun58** [comment]
@sunnylqm   **error**是不是就是没有找到的意思

**Comment by sunnylqm** [comment]
NotFoundError就是没找到
你的控制台里有其他报错或者警告吗

**Comment by jun58** [comment]
> NotFoundError就是没找到
> 你的控制台里有其他报错或者警告吗

这个：

![image](https://user-images.githubusercontent.com/20509429/65499265-edd1a400-deef-11e9-98b5-3d6d41c4dd34.png)

**Comment by sunnylqm** [comment]
你的import写得对吗

**Comment by jun58** [comment]
![image](https://user-images.githubusercontent.com/20509429/65499514-5587ef00-def0-11e9-9d4a-0b4105e6421d.png)

**Comment by jun58** [comment]
抄的文档
![image](https://user-images.githubusercontent.com/20509429/65499603-751f1780-def0-11e9-984c-42b3bb2b4529.png)

**Comment by jun58** [comment]
刚刚测试了IOS上也是一样的问题，Android和IOS都是debug模式

**Comment by sunnylqm** [comment]
代码贴更完整点吧

**Comment by jun58** [comment]
额，我检查了一下，发现是我每次启动的时候都清空了storage，注释掉代码之后可以了，不好意思。。。
