### ISSUE TITLE
load后，then返回的是缓存的数据，请求回来最新的数据并没有返回。

### ISSUE THREAD

**Issue by LeeZC** [sunnylqm/react-native-storage#233]
如题，比如，load1后，then返回的是缓存的数据，请求回来最新的数据data1并没有返回，等到下一次load2，then返回的是data1，而最新load2请求回来的数据作为最新的缓存，等到下一次load才返回。

**Comment by sunnylqm** [comment]
所以问题是什么？

**Comment by LeeZC** [comment]
> 所以问题是什么？

呀，回复这么快，我的意思是每一次load，返回的都是本次request回来的数据。

**Comment by sunnylqm** [comment]
所以到底问题是什么？

**Comment by LeeZC** [comment]
> 所以到底问题是什么？

所以没问题了。。。。我自己的写法问题导致的问题。。。。。。。。
