### ISSUE TITLE
读取的方式是异步的

### ISSUE THREAD

**Issue by tofrookie** [sunnylqm/react-native-storage#24]
不能用async和await方式获取吗？
```
 async get(){
        var storage = new Storage();
        var user = await storage.load({key:'user'});
}
```
这样不行啊

**Comment by sunnylqm** [comment]
应该是可以的

**Comment by tofrookie** [comment]
@sunnylqm 我试了不行啊
返回的是个Promise

**Comment by sunnylqm** [comment]
不懂，到底具体碰到啥问题。await本来就是接promise。

**Comment by tofrookie** [comment]
@sunnylqm 恩是的，但我返回的我刚打出来是这样的
Promise {_45: 0, _81: 0, _65: null, _54: null}

**Comment by sunnylqm** [comment]
具体一点好吗  打什么东西出来

**Comment by tofrookie** [comment]
@sunnylqm 没事了，我知道怎么用了，谢啦O(∩_∩)O~
我是之前 return了load的值，那样不对

**Comment by stevefermi** [comment]
@tofrookie 怎么用？不能接load的值的话，应该怎么接呢。

**Comment by kearons** [comment]
同问啊，

**Comment by wangfpp** [comment]
@tofrookie  你怎么用的啊可以贴出来吗
