### ISSUE TITLE
Request - Publish 1.0.1

### ISSUE THREAD

**Issue by miblanchard** [sunnylqm/react-native-storage#242]
@sunnylqm would it be possible to publish a new version of this package?  Looks like you have landed many nice changes since 1.0.0-beta was published.  I realize I can point to a commit, but wanted to ask about publishing a new version before we do that. Thank you for this package!

**Comment by sunnylqm** [comment]
Thanks for reminding but 1.0.1 was published 9 months ago and no meaningful commits since then

**Comment by miblanchard** [comment]
My mistake. I was looking at the release tags on the GitHub page. I see it on npm now.  Thanks again.
