### ISSUE TITLE
如何同步获取数据？

### ISSUE THREAD

**Issue by xdlgj** [sunnylqm/react-native-storage#244]
//用来管理当前登录用户的reducer函数 
const initUser = AsyncStorage.getItem(USER_KEY) 
function user (state = initUser, action) {
  switch (action.type) {
    case REVICE_USER:
      return action.user
    case RESET_USER:
      return {}
    default:
      return state
  }
}

**Comment by sunnylqm** [comment]
如果是redux，建议配合redux-persist使用，不用自己操心怎么存取

**Comment by sunnylqm** [comment]
直接用的话，要么`await`，要么`then`，没有别的用法

**Comment by orzhtml** [comment]
如果没有存数据，let res = await storage.load({ key: 'theme' })  会报错

**Comment by sunnylqm** [comment]
@orzhtml 有其他问题可以另外开个issue具体说一下吗？
