### ISSUE TITLE
Will I lost data on expire time change?

### ISSUE THREAD

**Issue by lahmacun** [sunnylqm/react-native-storage#249]
Hello, thanks for library. Great work.
It's a little urgent question. I'm going to release new version tomorrow and I changed my expire time from 1 day to null. Will my users lose data on during update?
Thank you very much.
Best Regards

**Comment by sunnylqm** [comment]
The change will only effect new data

**Comment by lahmacun** [comment]
Thanks for your response. Have a nice day.
