### ISSUE TITLE
ERROR: The modules ['@react-native-community_async-storage', 'react-native-community_async-storage'] point to the same directory in the file system. Each module must have a unique path.

### ISSUE THREAD

**Issue by shaxus** [sunnylqm/react-native-storage#254]
Hello, I followed the official installation steps to install react-native-storage and @react-native-community/async-storage, and then build in androidstuio, but reported an error ERROR: The modules ['@react-native-community_async-storage' ,'react-native-community_async-storage'] point to the same directory in the file system.
Each module must have a unique path.
![image](https://user-images.githubusercontent.com/37354089/91627493-64253300-e9ea-11ea-908d-bba931fb06a0.png)

**Comment by sunnylqm** [comment]
https://github.com/react-native-community/async-storage/issues/302#issuecomment-590823108

**Comment by shaxus** [comment]
I tried it, deleted @react-native-community_async-storage, and reopened androidstuio build, the error disappeared.
