### ISSUE TITLE
Unhandled JS Exception: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

### ISSUE THREAD

**Issue by hyy6565** [sunnylqm/react-native-storage#267]
environment：RN0.59

follow the .md file ,when biuld the project It occurs.

**Comment by sunnylqm** [comment]
only rn >= 0.60 has autolink feature. for version < 0.60 you should do manual linking (usually you just need to run `npx react-native link`) for all libraries that have native modules

ref: 
https://react-native-async-storage.github.io/async-storage/docs/install#link
