### ISSUE TITLE
How to Ignore expiry 

### ISSUE THREAD

**Issue by Kyu** [sunnylqm/react-native-storage#268]
Is it possible to get the details of an expired key?

or, if not, is it possible to load the current expired object inside of the `sync` function?

**Comment by sunnylqm** [comment]
what's your use case?

**Comment by Kyu** [comment]
My api has an exposed last_updated key. 

I plan to ping that last_updated endpoint and check if its greater than my current last_updated. If its not, then the sync function will return the current local version of the key, as nothing has changed. 


This is to save user bandwith

**Comment by sunnylqm** [comment]
This sounds weird, and i've never seen such design. Why bother to check the last_updated on client? Why not do it on server? in this way:
1. you save more code on client
2. more flexiable to control the update interval on server anytme
3. save roundtrip in just one call (return new data or no in just one api call. in your proposal you should do 2 right? first check then fetch)
4. avoid unintended calls from external parties (if any)

**Comment by Kyu** [comment]
The server has no way of knowing if the client has the most updated info.  

I could check via auth, but users are not required to authenticate to log in

**Comment by Kyu** [comment]
i just want a way to refresh the expiry date of an object without making an expensive call. I will try to create my own fork with this functionality
