### ISSUE TITLE
storage can not save Set Type

### ISSUE THREAD

**Issue by vivianking6855** [sunnylqm/react-native-storage#28]
when i use it to save Set, I can't get Set type when load it
-------------------------save
 let history = new Set();
        history.add('test');

        // save storage
        gstorage.save({
            key: CONS.STORAGE_SEARCH_KEY,  // Note: Do not use underscore("_") in key!
            rawData: {
                history: history,
            },
            expires: null   // if set to null, then it will never expire.
        })

-----------------------------------load : _(this.store_history).isSet()) return false
import _ from 'lodash';
  gstorage.load({
            key: CONS.STORAGE_SEARCH_KEY,
        }).then(ret => {
            // found data goes to then()
            this.store_history = ret.history;
            console.log('gstorage.load search:' +_(this.store_history).isSet());
        }).catch(err => {
            // any exception including data not found 
            // goes to catch()
            console.log('gstorage.load search err: ' + JSON.stringify(err));
        });

**Comment by sunnylqm** [comment]
Set / Map are not supported now. RawData should be a serializable type(via JSON.stringnify)
There are some workarounds... but seems unnecessary. And things become more complicated when these structures nest within each other.
http://stackoverflow.com/questions/31190885/json-stringify-a-set
http://stackoverflow.com/questions/28918232/how-do-i-persist-a-es6-map-in-localstorage-or-elsewhere
