### ISSUE TITLE
将storage放到全局是不是需要react-native某个版本以上才行啊？

### ISSUE THREAD

**Issue by phonebird** [sunnylqm/react-native-storage#29]
你好，我使用
`global.storage = storage;`
将storage放在全局，
之后在其它地方直接使用
`storage.save({
          key: 'loginInfo',
          rawData: obj,
        });`
提示找不到storage这个变量，我想问一下是不是需要在使用的地方在import一下啊？如果这样的话，global这个还有什么用？

**Comment by sunnylqm** [comment]
没有版本要求。不需要import。
但注意语句有执行顺序，必须先声明，而后才能使用。
如果声明在使用之后，必然会报错找不到。

**Comment by phonebird** [comment]
我是直接创建一个js文件，内容如下，然后在另一个文件里使用，这样报找不到变量，请问这样有问题吗？应该怎样使用？@sunnylqm 
`import Storage from 'react-native-storage';
var storage = new Storage({
  // 最大容量，默认值1000条数据循环存储
  size: 1000,    
  // 数据过期时间，默认一整天（1000 * 3600 * 24 毫秒），设为null则永不过期
  defaultExpires: null,
  // 读写时在内存中缓存数据。默认启用。
  enableCache: true,
})
// 在全局范围内创建一个（且只有一个）storage实例，方便直接调用
// 这样在之后的任意位置即可以直接调用storage
global.storage = storage;`
在另一个文件
`storage.save({
key: '',
rowData: {
}
})`

**Comment by phonebird** [comment]
我是直接创建一个js文件，内容如下，然后在其它js文件中直接使用storage，这样有问题吗？该怎样使用？
@sunnylqm 
`import Storage from 'react-native-storage';
var storage = new Storage({
  size: 1000,
  defaultExpires: null,
  enableCache: true,
})
global.storage = storage;`

**Comment by sunnylqm** [comment]
你创建一个js文件可以没问题，——然而它什么时候执行呢，以及甚至它到底执行过没？？
你要在某个必定会执行的文件（比如index.ios.js）中import这个文件才能保证这个文件不是一个孤立的没运行的文件啊

**Comment by mxkedr** [comment]
你好。请问下 有react-native-storage Demo吗？初学者 求一份  急  跟着git上介绍来  写下来是错误的 希望求一份demo 先谢谢了。

**Comment by sunnylqm** [comment]
@mxkedr 文档里就是demo直接可运行啊，具体有什么错自己开个issue贴出来啊。

**Comment by Rcrosp** [comment]
怎么申明，import storage from './app/utils/RTStorage'; 在入口 报错

**Comment by sunnylqm** [comment]
@Rcrosp 具体有什么错自己开个issue贴出来

**Comment by XIAOYAYAYAYA** [comment]
你好，问下 如果使用key  id 方式存储数据， id 可以实现自增长吗？还是每次增加一条都需要自己设定id的值呢？

**Comment by sunnylqm** [comment]
@XIAOYAYAYAYA 看不懂什么叫自己另外开个issue吗？ 没有自增长，这不是数据库。

**Comment by meijingkang** [comment]
@sunnylqm 
![qq 20170721180714](https://user-images.githubusercontent.com/15361537/28459321-8c722dba-6e3f-11e7-8523-b99b6c11ae26.png)
我按照你说的去做还是不行

**Comment by sunnylqm** [comment]
@meijingkang
1、请另开issue
2、报错了说明了，文档里也注明了，sync文件是你自己写的！

**Comment by WhoJave** [comment]
@meijingkang 你的问题解决了么

**Comment by caozhepeng** [comment]
@phonebird   你这样创建一个js文件声明的这个storage，在其他文件中怎么拿到这个storage

**Comment by lizhuoyuan** [comment]
就是说 在index.js里
import './xx/Storage.js'

在使用的地方
storage.setItem()...

**Comment by 291410392** [comment]
@sunnylqm 在class中使用有效，外部会报错，请问大佬啥情况
