### ISSUE TITLE
support native for android?

### ISSUE THREAD

**Issue by superlbr** [sunnylqm/react-native-storage#3]
feature

**Comment by sunnylqm** [comment]
Well, isn't android using the same AsyncStorage API? 
If yes, then this module should be ok to use. 
If no, could you please post some error info or references here?

**Comment by superlbr** [comment]
Maybe it's better to distinguish data no found with catch error

**Comment by sunnylqm** [comment]
I don't quite get your point...
Distinguish what from what?

**Comment by superlbr** [comment]
catch any exception including data not found ...
not found is not exception,i guess.

**Comment by sunnylqm** [comment]
https://github.com/search?utf8=%E2%9C%93&q=Notfoundexception&type=Code&ref=searchresults
