### ISSUE TITLE
storage+redux, sync对象中的方法如何传递参数

### ISSUE THREAD

**Issue by avivaWang** [sunnylqm/react-native-storage#31]
storage.sync = {
    myAttentionData(dispatch) {
        fetch(REQUEST_URL)
            .then(response => response.json())
            .then(responseData => {
                dispatch(endFetchData(responseData.itemlist));
                storage.save({
                    key: 'myAttentionData',
                    rawData: responseData.itemlist
                });
            })
            .done();
    }
}

怎么才能把dispatch传过去呢？

**Comment by sunnylqm** [comment]
我建议你在load之后dispatch，而不是在sync中
