### ISSUE TITLE
数据是异步读取的

### ISSUE THREAD

**Issue by kearons** [sunnylqm/react-native-storage#35]
看之前有位仁兄也提了这个问题，然而他说懂了就走了。。。
现在我的问题是，我的数据比如UUID是必须在主程序走之前加载完成，但是then链式调用，好像会先返回一个promise，主程序就开始走，之后才会执行then里面的，返回UUID，但是这样就错过了。用了async/await 也是这样。想问下，到底怎么样才能让我先取到数据再执行后面的程序，后面等待状态。菜鸟在线等

**Comment by sunnylqm** [comment]
如果你的UI必须先等待UUID再开始渲染，那你就必须等。就是在then之前，你用初始state控制显示个loading或者什么的。

**Comment by kearons** [comment]
我的并不是组件里面需要，嗯...只能折中一下，启动的时候就预读出UUID，放入全局变量，后面再读全局变量了
