### ISSUE TITLE
Error: Not found! Params:

### ISSUE THREAD

**Issue by jsntghf** [sunnylqm/react-native-storage#38]
![1](https://cloud.githubusercontent.com/assets/182790/18121984/d1141b36-6f99-11e6-94f5-339d1eebfac3.jpg)

just call Storage.load({ key: 'userInfo' })

sometimes its ok and can get data from storage, but sometimes its error.

why?

@sunnylqm

**Comment by sunnylqm** [comment]
Paste your code here

**Comment by jsntghf** [comment]
@sunnylqm 

`Storage.load({ key: 'userInfo' }).then(
  data => {
    console.log(data);
  }
).catch(
  error => {
    console.log(error);
  }
);`

global Storage code

`import Storage from 'react-native-storage';

global.Storage = new Storage({
  size: 1000,
  expires: null,
});`

im sure the storage is not null, the data is { userId: 'S2', password: '1' }, sometimes the code output { userId: 'S2', password: '1' }, sometimes it returned error

**Comment by sunnylqm** [comment]
Code seems normal. Maybe you have switched between debug and release mode? They have different storage.

**Comment by jsntghf** [comment]
@sunnylqm 
no, i always run on the same mode, sometimes it returned error and show red box, then i stopped it and run again, returned { staffId: 'X1', password: '1' }, but not change code and run on the same mode.

**Comment by sunnylqm** [comment]
A second look at your screen shot, it's weird that data had actually returned. Thanks for your feedback, I am investigating and will fix it today.

**Comment by sunnylqm** [comment]
Can you pack your project without node_modules and send it here? Thank you @jsntghf

**Comment by jsntghf** [comment]
sorry, the company project is private, not open source. @sunnylqm

**Comment by jsntghf** [comment]
The red box shows storage contains data, i think if data is not null, should returned data correctly. @sunnylqm

**Comment by sunnylqm** [comment]
It might be an "expired" error (which was a mistake to output "not found"). Can you confirm that? @jsntghf

**Comment by jsntghf** [comment]
The storage is unstable, if it might be expired, i think all the other storages might be expired, but another problem, the key is Info, i stored firstLaunch、companyCode、companyName, when i load data, sometimes it returned firstLaunch、companyCode、companyName, but sometimes it only returned firstLaunch, companyCode and companyName returned null. why?
and global storage setted expires as null, which means never expire.

**Comment by jsntghf** [comment]
react native version is 0.30.0 @sunnylqm

**Comment by sunnylqm** [comment]
I saw an expires value in the data, which meant that __defaultExpires__ was not null. It's **defaultExpires**, not **expires**. @jsntghf

**Comment by jsntghf** [comment]
react-native-storage version is 0.1.2, i saw this version used expires, in version 0.1.3, use defaultExpires.

a question, if expired, how can the red box show the data i saved and why the storage load data correctly when i run again?  @sunnylqm

**Comment by jsntghf** [comment]
`Storage.getAllDataForKey('userInfo').then(user => {`
    `console.log(user);`
`});`

this code output []

`Storage.load({ key: 'userInfo' }).then(user => {`
    `console.log(user);`
`});`

this code output { staffId: 'X1', password: '1' }

just for a test.

is this normal?  @sunnylqm

**Comment by jsntghf** [comment]
in version 0.1.2

document showed

`global.Storage = new Storage({`
`size: 1000,`
`expires: null,`
`});`

used key expires, i read the source code(save function), i think we'd use key defaultExpires.

is this right?

if this is the reason, i suggest update the document and demo code.

@sunnylqm

**Comment by sunnylqm** [comment]
In constructor (for global default setting), it's **defaultExpires**. And in save method, it's **expires** (for individual setting). These parameters have never changed through versions. getAllDataForKey is for "key-id" data, not "key-only" data, so this is normal. @jsntghf

**Comment by sunnylqm** [comment]
I can't reproduce your problem (once red box and the next time normal). Please check if you had called save or sync when re-run. And give me a minimal case if possible, thanks! @jsntghf
