### ISSUE TITLE
Saving data only works one time

### ISSUE THREAD

**Issue by waleedarshad-vf** [sunnylqm/react-native-storage#42]
when i remove application from task manager and start it again. saving data is not retrievable.

for example. when i saved
	storage.save({ key: 'authentication', rawData: authentication });
and retrieve immediately using load it works and i get data but when i close application and come back calling load method does not return saving data. what can be the reason?

**Comment by sunnylqm** [comment]
1、expired
2、no storageBackend provided
3、toggled debug mode (different storage)
4、deprecated buggy version (now is 0.1.4)

**Comment by waleedarshad-vf** [comment]
YEs not storageBackend provide that was the issue. i am not sure it was working previously without providing any storage backend.

in react native 0.27.2

**Comment by sunnylqm** [comment]
Yes, it was required in recent versions.

**Comment by zhaixiaoou** [comment]
how provide storage backend ?  can provide in react native 0.27.2 ? @sunnylqm

**Comment by sunnylqm** [comment]
@zhaixiaoou see the doc. And open a `new` issue if you have question.
