### ISSUE TITLE
sync里面怎么传递到load里？

### ISSUE THREAD

**Issue by jinghun1999** [sunnylqm/react-native-storage#43]

**Comment by jinghun1999** [comment]
//方法接受的参数为一整个object，所有参数从object中解构取出
                        //这里可以使用promise。或是使用普通回调函数，但需要调用resolve或reject。
这里不是很理解。

**Comment by sunnylqm** [comment]
参数是一整个object，其中含有id, resolve, reject三个值，照着例子写即可。
id就是load中的id值。
你在sync方法中如果成功获得数据，那么调用resolve(数据)把数据传回去，否则调用reject()表示失败

**Comment by jinghun1999** [comment]
那么sync方法一般放在什么地方呢？我这里load过期了会自动调用sync，但需要再次刷新页面才能load出来，
`storage.save({
                        key: 'USER',
                        rawData: {
                            user: data.Message,
                        },
                        expires: 1000 * 10,
                    });
                    storage.sync = {
                        USER(params){
                            let {id, resolve, reject } = params;
                            NetUtil.get(CONSTAPI.LOGIN + "?identity=18307722503&password=abc123&type=m", false, function (r) {
                                if (r.Sign && r.Message) {
                                    //Alert.alert('tips',JSON.stringify(r.Message));
                                    storage.save({
                                        key: 'USER',
                                        id,
                                        rawData: {
                                            user: r.Message,
                                        },
                                        expires: 1000 * 10,
                                    });
                                    // 成功则调用resolve
                                    resolve && resolve({user: r.Message});
                                }
                                else {
                                    // 失败则调用reject
                                    reject && reject(new Error('data parse error'));
                                }
                            }).catch(err => {
                                Alert.alert('提示', err);
                                //reject && reject(err);
                            });
                        }
                    }`



`storage.load({
            key: 'USER',
            autoSync: true,
            syncInBackground: false
        }).then(user => {
            storage.load({
                key: 'HOSPITAL',
                autoSync: false,
                syncInBackground: false
            }).then(hos=> {
                success(user, hos);
            }).catch(e=> {
                switch (e.name) {
                    case 'NotFoundError':
                        error('请先设置默认医院');
                        break;
                    case 'ExpiredError':
                        error('默认医院已过期');
                        break;
                    default :
                        error('请重新登陆应用1');
                        break;
                }
            })
        }).catch(err => {
            switch (err.name) {
                case 'NotFoundError':
                    error('not found user');
                    break;
                case 'ExpiredError':
                    error('user login expired');
                    break;
                default :
                    error('请重新登陆应用');
                    break;
            }
        });`

**Comment by sunnylqm** [comment]
1、sync就是Storage下的一个属性，你可以在构造时声明，可以在任何时候任何地方声明。但你完全不需要在save时声明（不然岂不是每次save时都声明一次？没必要啊）
2、promise的好处就是可以链式调用而不必嵌套，因此错误可以统一处理，你的load代码可以简化为
```
storage.load({
            key: 'USER',
            autoSync: true,
            syncInBackground: false
        }).then(user => {
            return storage.load({
                key: 'HOSPITAL',
                autoSync: false,
                syncInBackground: false
            })
        }).then(hos=> {
                success(user, hos);
        }).catch(err => {
            switch (err.name) {
                case 'NotFoundError':
                    error('not found user');
                    break;
                case 'ExpiredError':
                    error('user login expired');
                    break;
                default :
                    error('请重新登陆应用');
                    break;
            }
        });
```
3. 不明白“但需要再次刷新页面才能load出来”具体是什么意思

**Comment by jinghun1999** [comment]
刚才代码格式太乱，重新发以下。
```
storage.load({
            key: 'USER',
            autoSync: true,
            syncInBackground: false
        }).then(user => {
            storage.load({
                key: 'HOSPITAL',
                autoSync: false,
                syncInBackground: false
            }).then(hos=> {
                success(user, hos);
            }).catch(e=> {
                switch (e.name) {
                    case 'NotFoundError':
                        error('请先设置默认医院');
                        break;
                    case 'ExpiredError':
                        error('默认医院已过期');
                        break;
                    default :
                        error('请重新登陆应用1');
                        break;
                }
            })
        }).catch(err => {
            switch (err.name) {
                case 'NotFoundError':
                    error('not found user');
                    break;
                case 'ExpiredError':
                    error('user login expired');
                    break;
                default :
                    error('请重新登陆应用');
                    break;
            }
        });
```
save & sync
```
storage.save({
                        key: 'USER',
                        rawData: {
                            user: data.Message,
                        },
                        expires: 1000 * 10,
                    });
                    storage.sync = {
                        USER(params){
                            let {id, resolve, reject } = params;
                            NetUtil.get(CONSTAPI.LOGIN + "?identity=18307722503&password=abc123&type=m", false, function (r) {
                                if (r.Sign && r.Message) {
                                    //Alert.alert('tips',JSON.stringify(r.Message));
                                    storage.save({
                                        key: 'USER',
                                        id,
                                        rawData: {
                                            user: r.Message,
                                        },
                                        expires: 1000 * 10,
                                    });
                                    // 成功则调用resolve
                                    resolve && resolve({user: r.Message});
                                }
                                else {
                                    // 失败则调用reject
                                    reject && reject(new Error('data parse error'));
                                }
                            }).catch(err => {
                                Alert.alert('提示', err);
                                //reject && reject(err);
                            });
                        }
                    }
```

**Comment by jinghun1999** [comment]
就是sync后不能及时传递给load方法的then里，

**Comment by sunnylqm** [comment]
请贴具体的代码和判断的依据

**Comment by jinghun1999** [comment]
你改的代码里user取不到的。
···
storage.sync = {
                        USER(params){
                            let {id, resolve, reject } = params;
                            NetUtil.get(CONSTAPI.LOGIN + "?identity=18307722503&password=abc123&type=m", false, function (r) {
                                if (r.Sign && r.Message) {
                                    //Alert.alert('tips',JSON.stringify(r.Message));
                                    storage.save({
                                        key: 'USER',
                                        id,
                                        rawData: {
                                            user: r.Message,
                                        },
                                        expires: 1000 * 10,
                                    });
                                    // 成功则调用resolve
                                    resolve && resolve({user: r.Message});
                                }
                                else {
                                    // 失败则调用reject
                                    reject && reject(new Error('data parse error'));
                                }
                            }).catch(err => {
                                Alert.alert('提示', err);
                                //reject && reject(err);
                            });
                        }
                    }
···
这里sync成功后不能及时返回给load方法里取得sync的值

**Comment by jinghun1999** [comment]
```
storage.sync = {
USER(params){
let {id, resolve, reject } = params;
NetUtil.get(CONSTAPI.LOGIN + "?identity=18307722503&password=abc123&type=m", false, function (r) {
if (r.Sign && r.Message) {
//Alert.alert('tips',JSON.stringify(r.Message));
storage.save({
key: 'USER',
id,
rawData: {
user: r.Message,
},
expires: 1000 * 10,
});
// 成功则调用resolve
resolve && resolve({user: r.Message});
}
else {
// 失败则调用reject
reject && reject(new Error('data parse error'));
}
}).catch(err => {
Alert.alert('提示', err);
//reject && reject(err);
});
}
}
```
重新格式化下上面代码

**Comment by jinghun1999** [comment]
重新格式化下上面代码
```
storage.sync = {
                        USER(params){
                            let {id, resolve, reject } = params;
                            NetUtil.get(CONSTAPI.LOGIN + "?identity=18307722503&password=abc123&type=m", false, function (r) {
                                if (r.Sign && r.Message) {
                                    //Alert.alert('tips',JSON.stringify(r.Message));
                                    storage.save({
                                        key: 'USER',
                                        id,
                                        rawData: {
                                            user: r.Message,
                                        },
                                        expires: 1000 * 10,
                                    });
                                    // 成功则调用resolve
                                    resolve && resolve({user: r.Message});
                                }
                                else {
                                    // 失败则调用reject
                                    reject && reject(new Error('data parse error'));
                                }
                            }).catch(err => {
                                Alert.alert('提示', err);
                                //reject && reject(err);
                            });
                        }
                    }
```

**Comment by sunnylqm** [comment]
你插个断点或者log在load的then里看看返回的是什么，还是没有返回？如果是不触发断点或者打印，我怀疑是debug模式的问题。你可以关闭debug，然后改成alert调试。

**Comment by sunnylqm** [comment]
如果没有问题就先关闭了。
