### ISSUE TITLE
数据过期时间，默认一整天（1000 * 3600 * 24 毫秒），设为null则永不过期

### ISSUE THREAD

**Issue by tanpuer** [sunnylqm/react-native-storage#44]
求教
1. 过期的数据怎么处理的呢？直接删除？

2.数据过期时间是指整个storage还是其中的单个数据？

**Comment by sunnylqm** [comment]
1、不会删除，只是会触发sync或抛异常走catch
2、总体有个默认值，单个可覆盖默认值

**Comment by tanpuer** [comment]
那就是说，过期的数据还算在 app的存储空间里了？
默认1000条数据，到1001条时，会删除覆盖1号数据吗？

最近想控制asyncstorage的整体大小，不知道怎么入手。。。

**Comment by sunnylqm** [comment]
请仔细读文档吧，都说明了
