### ISSUE TITLE
JSON value '<null>' of type NSNull cannot be converted to NSString

### ISSUE THREAD

**Issue by devjiangzhou** [sunnylqm/react-native-storage#46]
load 数据为空时会报这个错

export const UNIONID = 'UNIONID';

let storage = new Storage({
  size: Number.MAX_SAFE_INTEGER,
  storageBackend: AsyncStorage,
  defaultExpires: null,
  enableCache: true,
  sync: {
  }
});

module.exports = {
  Storage : storage
};

Global.Storage.load({
      key: Global.UNIONID
    }).then(ret => {
      navigator.resetTo({ id: 'Home' });
    }).catch(err => {
      navigator.resetTo({ id: 'Activate' });
    });

**Comment by wangshijun** [comment]
@devjiangzhou 这个后来是怎么解决的？

**Comment by marlti7** [comment]
同问，怎么解决的
