### ISSUE TITLE
react-native 模拟器里有方式可以快速清除 storage 吗

### ISSUE THREAD

**Issue by xwartz** [sunnylqm/react-native-storage#47]
只能手动调用方法吗

**Comment by sunnylqm** [comment]
chrome的console里可以调用啊（如果你把storage放在全局的话）

**Comment by xwartz** [comment]
好吧，仔细一看那个项目并没有使用你的这个模块，用了 RN 原生的 AsyncStorage API...

放在全局 window 好像也是取不到

**Comment by sunnylqm** [comment]
全局肯定可以取到的
https://github.com/sunnylqm/react-native-storage/issues/29
