### ISSUE TITLE
同一个key用不同的id存储数据，之后取出来的是个什么类型的数据哦？好像不是数组

### ISSUE THREAD

**Issue by lwcla** [sunnylqm/react-native-storage#49]
// 获取某个key下的所有数据
storage.getAllDataForKey('user').then(users => {
    console.log(users);
});

同一个key用不同的id存储数据，用上面的方法取出来的好像不是个数组，也不是个对象。。。

**Comment by lwcla** [comment]
getBatchData(querys) {
    let me = this;
    let tasks = [];
    for(let i = 0, query; query = querys[i]; i++) {
      tasks[i] = me.load(query);
    }
    return Promise.all(tasks);
  }

我看到返回的是个数组，但是用下标打印出来是undefined。。。奇怪

**Comment by lwcla** [comment]
代码下下来看了半天。。。
storage.save({
    key: 'user',  // 注意:请不要在key中使用_下划线符号!
    id: '1001',   // 注意:请不要在id中使用_下划线符号!
    rawData: userA,   //这个地方只能用rawData，我自定义了一个其他的名字，结果就存不进去了，尴尬
    expires: 1000 * 60   
  });

**Comment by sunnylqm** [comment]
所以解决了是吗？

**Comment by lwcla** [comment]
是的，已经解决了，不过还是想要写在这里，免得其他同学遇到这样的问题不知道错在哪里。。

**Comment by sunnylqm** [comment]
我觉得一般不会出这样的错误。。。

**Comment by lwcla** [comment]
这就比较尴尬了。。
