### ISSUE TITLE
Max capacity (size) - what are the units? 

### ISSUE THREAD

**Issue by tomcelinski** [sunnylqm/react-native-storage#50]
Hi,

When setting the maximum capacity via size (e.g. size: 1000), what are the assumed units? Is this the number of key/value pairs? Or total bytes? Or something else? 

Thank you in advance for your clarification.

Tom

**Comment by sunnylqm** [comment]
Only key-id data.
https://github.com/sunnylqm/react-native-storage/issues/32

**Comment by tomcelinski** [comment]
So does this mean that setting "size:1000" allows a maximum of 1000 key-ids? So effectively this means we can store 1000 key/data pairs? Is my understanding correct?

**Comment by sunnylqm** [comment]
You can store 1000 key-ids. 
Key-only data are unlimited.
