### ISSUE TITLE
size 的问题 

### ISSUE THREAD

**Issue by cham1985** [sunnylqm/react-native-storage#54]
// 最大容量，默认值1000条数据循环存储
  size: 1000,

问下,  size 是 数据库里 最多1000个表, 还是 每个表里 最多 1000条数据 ?

**Comment by sunnylqm** [comment]
1000条key-id数据

**Comment by cham1985** [comment]
一个 key 可以理解为 一个表么,  一个id 可以 理解为一个表里的一条数据么? 那  1000条key-id数据 的意思是不是 数据库里 所有表里的 数据 加起来?

**Comment by sunnylqm** [comment]
没有表的概念

所有的key-id数据加起来1000条

**Comment by sunnylqm** [comment]
不能

**Comment by cham1985** [comment]
![image](https://cloud.githubusercontent.com/assets/7087874/20787387/7f859872-b7e6-11e6-9f32-ce859b5a4fc5.png)

可以这么理解么,  '所有的key-id数据加起来1000条 ' 的意思是 同类别（key) 下的 所有 id 数据加起来 还是 所有 类别的 key 下 的 所有id  加起来 ?

**Comment by sunnylqm** [comment]
所有类别

**Comment by cham1985** [comment]
缓存的数据库文件有 工具 可以 直观 的看到数据结构吗?

**Comment by cham1985** [comment]
![image](https://cloud.githubusercontent.com/assets/7087874/20787704/41f9470e-b7e8-11e6-844e-a31516b326aa.png)
这个 id 没复制, 和

**Comment by cham1985** [comment]
![image](https://cloud.githubusercontent.com/assets/7087874/20787723/6469be40-b7e8-11e6-8985-708a2910f50e.png)
这个id 没赋值, 和 
storage.save({
            key: 'user',
            id: id
            rawData: json.user
          });
效果一样吗?

**Comment by sunnylqm** [comment]
目前没有工具可以直接看
id: id  在es6中可以简写为一个id

**Comment by cham1985** [comment]
O(∩_∩)O谢谢

**Comment by sunnylqm** [comment]
不过debug/web模式下可以使用window.localStorage，然后在chrome中可以看到数据
![qq 20161201171101](https://cloud.githubusercontent.com/assets/615282/20787903/364107b6-b7e9-11e6-861a-e4a04ef2f78f.png)

**Comment by cham1985** [comment]
我是 debug/ RN 模式,  应该暂时看不到吧
