### ISSUE TITLE
How exactly does defaultExpires/expires work?

### ISSUE THREAD

**Issue by sood03** [sunnylqm/react-native-storage#57]
In my store declaration, I have mentioned defaultExpires : 10 (10 milliseconds) just to test that if the data is not available in store, it should fetch the new data. But this logic doesn't seem to work. I have tried using expires: 10 in each save but that also doesn't work.

This is my store declaration :

export default storeData = new Storage({
    size : 1000,
    storageBackend : AsyncStorage,
    defaultExpires : 10,
    enableCache : true,
    sync : {

    }
});

This is my store saving data

storeData.save({
                                key: 'token',
                                rawData: {
                                    token: jsonData.id_token
                                },
                                expires: 10
});

Here I am checking for token. In case it is not present, I fetch a new one

storeData.load({
            key: 'token',
            autoSync: true,
            syncInBackground: true
        }).then(user => {
            console.log("token already found in store: " + user.token);
        }).catch(err => {
            console.log("error : " + err.name);
            switch (err.name) {
                case 'ExpiredError':
                case 'NotFoundError':
                    console.log("token not found/expired. fetching new");
            }
        });

But everytime I load the app, I get "token already found in store". 

How do I expire the token?

**Comment by sunnylqm** [comment]
`syncInBackground`(default true) means if data expired, return the outdated data first and then invoke the sync method.
It can be set to false to always return data provided by sync method or throw error when expired. (Of course it's slower)

**Comment by sood03** [comment]
I am wondering how do I make my data expire intentionally? I want to check the code flow when the data is found in store and when it is not.

I have tried setting syncInBackground : false, defaultExpire : 10. So this should mean, as soon as I save my data, in 10 ms, that data should expire. Then if I make a new call to  load that data, 'ExpiredError' should be thrown. But this is not happening.

As you told, on loading the data, in case it is not found, either the sync methods should be called or ExpiredError should be thrown. As I have not set any sync method, 'ExpiredError' is the only option left which should be executed but I don't see that happening.

**Comment by sunnylqm** [comment]
Sounds weird.  
Can you post complete code or package your entire project (without node_modules) here?

**Comment by sood03** [comment]
I increased the expire duration to 1000*3600 and found the logic is working as expected. It seems for low expiration duration, this issue occurs. Anyways, i was just testing the expiration logic which seems to be working for expiration set to 1 hour. 
Will close it for now. Thanks :)
