### ISSUE TITLE
安装了无法导入：Unkown named module:'react-native-storage'

### ISSUE THREAD

**Issue by tooodooo** [sunnylqm/react-native-storage#58]
RN版本0.39

安装后就报这个错，注释掉这行就可以运行，什么问题呢？谢谢

`import Storage from 'react-native-storage';`

**Comment by sunnylqm** [comment]
一般来说是你没有成功安装（检查node_modules目录下是否有react-native-storage这个目录）
或者可能需要重启packager

**Comment by tooodooo** [comment]
应该是安装成功了，目录下存在react-native-storage这个目录

**Comment by sunnylqm** [comment]
贴一下报错的截图和目录结构的截图

**Comment by tooodooo** [comment]
<img width="199" alt="2016-12-04 9 44 12" src="https://cloud.githubusercontent.com/assets/6067607/20866688/b9d547dc-ba6d-11e6-9495-b85adfb24c47.png">

这里显示目录为快捷方式，不知道是不是这个原因
<img width="150" alt="2016-12-04 9 45 32" src="https://cloud.githubusercontent.com/assets/6067607/20866690/bc8230c6-ba6d-11e6-9268-8f16563a1a6b.png">
<img width="137" alt="2016-12-04 9 45 58" src="https://cloud.githubusercontent.com/assets/6067607/20866691/c48adef8-ba6d-11e6-80f7-4088274a1d15.png">

**Comment by sunnylqm** [comment]
https://github.com/facebook/react-native/issues/637  这个issues提到了，symlink（快捷方式）会导致这个报错
问题是你是做了什么操作导致这个目录变成symlink？
然后上面那个issue提到官方有个补丁 https://github.com/facebook/react-native/commit/fa6191f6ac65a8a303a22933e183e1f5a7381976
意思大概是0.35开始支持了symlink，你目前的版本是否低于0.35？试试升级RN到0.35以上？

**Comment by tooodooo** [comment]
就是安装完执行了 
`npm link`
我的RN是0.39版本的，按说应该是支持的

**Comment by sunnylqm** [comment]
为什么要执行npm link？？

**Comment by tooodooo** [comment]
装其他一些模块的时候有的安装说明是要执行这条命令的，以为都要执行呢

**Comment by sunnylqm** [comment]
rn的模块应该是不用执行`npm link`的，部分原生模块需要执行的是`rnpm link`

**Comment by tooodooo** [comment]
学习了，多谢~
