### ISSUE TITLE
通过使用key和id保存的同类大量数据，怎么一次全量取出？

### ISSUE THREAD

**Issue by keyneko** [sunnylqm/react-native-storage#6]
通过使用key和id保存的同类大量数据，怎么一次全量取出？
没有保存id的数组

**Comment by sunnylqm** [comment]
使用getBatchData或者getBatchDataWithIds，后者需要服务器端接口能处理数组型数据

**Comment by sunnylqm** [comment]
你说的是id未知是吧。。。嗯  我想想怎么实现

**Comment by keyneko** [comment]
是的没id

**Comment by sunnylqm** [comment]
由于storage内部的map实现也是离散的，所以也没法直接获取到单个key下的全部id，如果是遍历map找同一key下的ids，那还不如你这样直接存一个全局的ids数组。既然有ids数组的话，那就可以用getBatchDataWithIds方法了。后续版本我会加上multiGet方法以优化批量数据的读取。

**Comment by keyneko** [comment]
嗯，好的了解了:)
