### ISSUE TITLE
Clear storage data

### ISSUE THREAD

**Issue by sood03** [sunnylqm/react-native-storage#61]
I have defined my storage as 
export default storeData = new Storage({
    size : 1000,
    storageBackend : AsyncStorage,
    defaultExpires : 1000*3600*24,
    enableCache : true,
});

storeData.clearMap() does not clear the data. So for now, I have to do something like 

storeData.remove({
   key: 'user'
});
storeData.remove({
   key: 'token'
});
storeData.remove({
   key: 'room'
});

Is there any way to clear all the keys along with data I have stored till now instead of removing one after another?

**Comment by sunnylqm** [comment]
Generally there is no need to remove key-only data. They should be important so even if removal is necessary, they should be removed one by one by design.
Frequent removal operations of key-only data sound quite anti-pattern, maybe they should be saved in key-id data form?

**Comment by sood03** [comment]
So I feel only way to clear the storage is to remove all the keys one after another?

**Comment by sunnylqm** [comment]
That's the case for now.
