### ISSUE TITLE
Does it support reactjs?

### ISSUE THREAD

**Issue by jaynakus** [sunnylqm/react-native-storage#66]
I have a project with shared codebase for native and web. On react-native it runs with no problem, but when I try to run on reactjs I get error.

`react-native-storage/storage.js Unexpected token (186:39)
You may need an appropriate loader to handle this file type.`

**Comment by jaynakus** [comment]
I loader is attached as new, so there are two js loaders. But the seconds tests only for storage.js

```
 module: {
    loaders: [
      // take all less files, compile them, and bundle them in with our js bundle
      {test: /\.less$/, loader: 'style!css!autoprefixer?browsers=last 2 version!less'},
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {
          presets: ['es2015', 'react'],
          plugins: [['react-transform', {
            transforms: [{
              transform: 'react-transform-hmr',
              imports: ['react'],
              // this is important for Webpack HMR:
              locals: ['module']
            }],
          }]],
        },
      },
      {
        test: /storage\.js?$/,
        include: [
          path.join(__dirname, 'node_modules/react-native-storage')
        ],
        loader: 'babel',
        query: {
          cacheDirectory: true,
          presets: ['es2015', 'stage-1', 'react'],
          plugins: ['transform-runtime']
        }
      }
    ],
  },
```

**Comment by sunnylqm** [comment]
try to modify the second test?

**Comment by jaynakus** [comment]
Ok the problem was with path recognition, so I modified path searching like this, now it works: 

```
 {
        test: /\.js?$/,
        include: /react-native-storage/,
        loader: 'babel-loader',
        query: {
          cacheDirectory: true,
          presets: ['es2015', 'react'],
          plugins: ['transform-runtime']
        }
 }
```

**Comment by mmahalwy** [comment]
I keep getting error too:
```
ERROR in ../mobile/~/react-native-storage/storage.js
Module parse failed: /Users/mmahalwy/Desktop/code/startups/chill/chill-app/mobile/node_modules/react-native-storage/storage.js Unexpected token (186:41)
You may need an appropriate loader to handle this file type.
|     if(this.enableCache && this.cache[key] !== undefined) {
|       ret = this.cache[key];
|       return this._loadGlobalItem({ ret, ...params });
|     }
|     return this.getItem(key).then(ret => this._loadGlobalItem({ ret, ...params }));
 @ ../mobile/utils/storage.js 1:81-112
 @ ../mobile/utils/createClient.js
 @ ./app/containers/Root.js
 @ ./app/index.js
```

**Comment by TiagoGouvea** [comment]
@mmahalwy did you solve it?

**Comment by mmahalwy** [comment]
I did not and gave up

**Comment by sunnylqm** [comment]
Try adding this plugin http://babeljs.io/docs/plugins/transform-object-rest-spread/
@TiagoGouvea @mmahalwy

**Comment by jaynakus** [comment]
@TiagoGouvea You should remove "exclude: /node_modules/" because it excludes everything in that folder

**Comment by sunnylqm** [comment]
@jaynakus No, "exclude: /node_modules/" is recommended. Compiling third libs is a big waste of time, so most libs choose to get precompiled and excluded . My storage lib is an exception.

**Comment by orelmax** [comment]
I've ended up with the next config for webpack 2.2.1.

```
module: {
    rules: [{
      test: /\.js$|\.jsx$/,
      exclude: /node_modules/,
      use: [{
        loader: 'babel-loader'
      }],
    }, {
      test: /\.js?$/,
      include: [
        path.join(__dirname, '../node_modules/react-native-storage'),
      ],
      use: [{
        loader: 'babel-loader',
        options: {
          cacheDirectory: true,
          presets: ['es2015', 'stage-1', 'react'],
          plugins: ['transform-runtime'],
        },
      }],
    }
```

**Comment by jaynakus** [comment]
as @orelmax provided in example. You should include react-native-storage in different rule/loader

**Comment by abdelav** [comment]
hey guys I run into the same issue and I decide to fork this repo and rewrite the code, with flow and other things, I don't want to look selfish or something but the reason is simple, is a code that we are going to keep using and maintaining inside of my company which is a fully react dom / react native company, please feel free to use it. Also, I split the code and is ease to read in case that some of you guys want to collaborate.

[react-hybrid-storage](https://github.com/dnamic/react-hybrid-storage)

this version will not require any webpack or babel configuration, feedback is very welcome.

**Comment by bala-compassites** [comment]
same issue getting. How to resolve this?

**Comment by frxncisjoseph** [comment]
I'd really like some insight, I'm also struggling with the same error...
