### ISSUE TITLE
建议enableCache设置为默认关闭

### ISSUE THREAD

**Issue by wh469012917** [sunnylqm/react-native-storage#67]
为什么要这么建议？我说个这样的例子：
比如我缓存了一个用户的数据，该数据大概是这样：
```
{
    id : 5,
    nickname: '张三',
    avatar: '/assets/avatar1.png'
}
```
上面的数据是用户的原始数据，但是假如我要根据不同的情景做一些改变，比如我在用户中心要这么显示：
```
【张三】
```
在其他地方又要这样显示：
```
{张三}
```

也就是说我可能会对获取到的数据进行修改后再显示，但是获取的却希望是原始的数据。

而这时如果开启enableCache的话，每次获取，都会是修改后的数据。所以建议：这个功能默认关闭

**Comment by sunnylqm** [comment]
不太明白这个和cache有什么关系？
'[' + object.nickname + ']'
'{' + object.nickname + '}'

**Comment by sunnylqm** [comment]
你的意思可能是你直接修改了object？
这是一种不好的模式/习惯
一般来说，在render时，首先解构
const  { id, nickname, avatar } = object;
然后根据需要，另用变量进行处理
const nameToRender = `【${nickname}】`

<Text>{nameToRender}</Text>

**Comment by wh469012917** [comment]
@sunnylqm 知道了，js的对象是按引用传递的，所以我在修饰的函数上操作会改变数据。使用解构的方式也是可以的，不过在对象数据比较多的情况下，而我只想对其中某个数据修改，这样最后再组装对象会麻烦点。

**Comment by sunnylqm** [comment]
比起每次都去storage里取，那也应该是深复制后修改

**Comment by wh469012917** [comment]
@sunnylqm 恩对的。
