### ISSUE TITLE
__keys__ is undefined after clearMap()

### ISSUE THREAD

**Issue by paulief** [sunnylqm/react-native-storage#69]
I've noticed that  `_m.__keys__` is not reset to an empty map after calling `clearMap()`:
```
me._m = {
  innerVersion: me._innerVersion,
  index: 0
};
```

 This leads to an issue on the next call to `save`. When `_saveToMap` is called, this line will throw an error as `m.__keys__` is undefined:
```
m.__keys__[key] = m.__keys__[key] || [];
```

It seems like `clearMap()` should set `__keys__` as an empty hash the same way as it is when constructing the Storage object in `_checkMap(map)`: 
```
return {
  innerVersion: me._innerVersion,
  index: 0,
  __keys__: {}
};
```
Is that correct or am I missing something? Happy to submit a small PR if this makes sense.

**Comment by sunnylqm** [comment]
I remember I've done that?  https://github.com/sunnylqm/react-native-storage/blob/master/storage.js#L325
Anything wrong with this?

**Comment by paulief** [comment]
@sunnylqm thanks for the quick response, I appreciate it.

Is that in version 0.1.4? It seems that's what's published to npm but I noticed a later version (0.1.5) on what you sent.
https://www.npmjs.com/package/react-native-storage

**Comment by sunnylqm** [comment]
0.1.5 is not yet published. You can install it by:
```
npm i https://github.com/sunnylqm/react-native-storage --save
```
for now

**Comment by paulief** [comment]
Awesome @sunnylqm, thank you
