### ISSUE TITLE
doesn't work with RN 0.20

### ISSUE THREAD

**Issue by chezhe** [sunnylqm/react-native-storage#7]
I upgrade RN from 0.18 to 0.20, and got this error

![default](https://cloud.githubusercontent.com/assets/2902414/13026063/7f436172-d255-11e5-8ed1-db5254c06ec1.jpg)

**Comment by chezhe** [comment]
I find ! I didn't catch the error while read data. It works fine. It's time to write ES6.
Thanks for your library!

**Comment by sunnylqm** [comment]
Enjoy!
