### ISSUE TITLE
如何判断key是否存在以及统计数量？

### ISSUE THREAD

**Issue by wh469012917** [sunnylqm/react-native-storage#70]
如题，如何判断一个key是否存在本地？是否只能去读取该数据然后通过是否有返回来判断？
使用场景：判断一本书的某个章节是否有缓存，以此来给用户相应的提示。

还有，如何统计某个key下有多少行数据呢？只能全部读取出来再统计吗？

**Comment by sunnylqm** [comment]
1. load后catch
2. getAllDataForKey

**Comment by chenyaw** [comment]
getAllDataForKey('user') 执行不了。要这样solve这个问题呀？

**Comment by sunnylqm** [comment]
@chenyaw  “执行不了”等于什么都没说

**Comment by wh469012917** [comment]
@chenyaw 方法执行不了，有一下这些情况：
1.方法不存在
2.调用该方法的对象为空
3.调用了但是报错了
4.没有任何反应

请问你的是哪种情况？请把你的代码，执行不了的过程，尝试的方法，以及相关错误日志贴上来
