### ISSUE TITLE
什么情况会出现NotFoundError

### ISSUE THREAD

**Issue by lxooxl** [sunnylqm/react-native-storage#71]
出现NotFoundError的时候不会调用sync.

**Comment by sunnylqm** [comment]
贴代码

**Comment by lxooxl** [comment]
`
storage.sync = {
            image(params) {
                let {id, resolve, reject} = params;
                fetch(id)
                    .then(response => response.blob())
                    .then(blob => {
                        let reader = new FileReader();
                        reader.addEventListener("loadend", () => {
                            if (!reader.error) {
                                storage.save({
                                    key: 'image',
                                    id,
                                    rawData: reader.result,
                                    expires:null,
                                    size: 100,
                                });
                                resolve && resolve(reader.result);
                            } else {
                                reject && reject(new Error('data parse error'))
                            }
                        });
                        reader.readAsBinaryString(blob);
                    })
                    .catch(err=>{
                        reject && reject(err);
                    });
            }
        };

        storage.load({
            key: 'image',
            id: this.props.source.uri,
        }).then(ret => {

            this.isMount && this.setState({
                imgSource: 'data:image/png;base64,' + base64.encode(ret),
            })
        }).catch(err => {
            console.log(err);
        })
`

**Comment by lxooxl** [comment]
`storage.sync = {
            image(params) {
                let {id, resolve, reject} = params;
                fetch(id)
                    .then(response => response.blob())
                    .then(blob => {
                        let reader = new FileReader();
                        reader.addEventListener("loadend", () => {
                            if (!reader.error) {
                                storage.save({
                                    key: 'image',
                                    id,
                                    rawData: reader.result,
                                    expires:null,
                                    size: 100,
                                });
                                resolve && resolve(reader.result);
                            } else {
                                reject && reject(new Error('data parse error'))
                            }
                        });
                        reader.readAsBinaryString(blob);
                    })
                    .catch(err=>{
                        reject && reject(err);
                    });
            }
        };

        storage.load({
            key: 'image',
            id: this.props.source.uri,
        }).then(ret => {

            this.isMount && this.setState({
                imgSource: 'data:image/png;base64,' + base64.encode(ret),
            })
        }).catch(err => {
            console.log(err);
        })`

**Comment by lxooxl** [comment]
`storage.sync = {
            image(params) {
                let {id, resolve, reject} = params;
                fetch(id)
                    .then(response => response.blob())
                    .then(blob => {
                        let reader = new FileReader();
                        reader.addEventListener("loadend", () => {
                            if (!reader.error) {
                                storage.save({
                                    key: 'image',
                                    id,
                                    rawData: reader.result,
                                    expires:null,
                                    size: 100,
                                });
                                resolve && resolve(reader.result);
                            } else {
                                reject && reject(new Error('data parse error'))
                            }
                        });
                        reader.readAsBinaryString(blob);
                    })
                    .catch(err=>{
                        reject && reject(err);
                    });
            }
        };
`
`
        storage.load({
            key: 'image',
            id: this.props.source.uri,
        }).then(ret => {

            this.isMount && this.setState({
                imgSource: 'data:image/png;base64,' + base64.encode(ret),
            })
        }).catch(err => {
            console.log(err);
        })
`

**Comment by lxooxl** [comment]
storage.sync = {
            image(params) {
                let {id, resolve, reject} = params;
                fetch(id)
                    .then(response => response.blob())
                    .then(blob => {
                        let reader = new FileReader();
                        reader.addEventListener("loadend", () => {
                            if (!reader.error) {
                                storage.save({
                                    key: 'image',
                                    id,
                                    rawData: reader.result,
                                    expires:null,
                                    size: 100,
                                });
                                resolve && resolve(reader.result);
                            } else {
                                reject && reject(new Error('data parse error'))
                            }
                        });
                        reader.readAsBinaryString(blob);
                    })
                    .catch(err=>{
                        reject && reject(err);
                    });
            }
        };

        storage.load({
            key: 'image',
            id: this.props.source.uri,
        }).then(ret => {

            this.isMount && this.setState({
                imgSource: 'data:image/png;base64,' + base64.encode(ret),
            })
        }).catch(err => {
            console.log(err);
        })

**Comment by sunnylqm** [comment]
sync断点不触发吗

**Comment by lxooxl** [comment]
嗯,是的.
`NotFoundError {name: "NotFoundError", message: "Not Found! Params: {"key":"filmList","id":"orderTy…&page=1","autoSync":true,"syncInBackground":true}", stack: "Error↵    at new NotFoundError (http://localhost:8…atform=ios&dev=true&minify=false&hot=true:37254:9"}`

**Comment by lxooxl** [comment]
好像不对. key不一样

**Comment by lxooxl** [comment]
我现在修改成这样了,
storage.sync = {
     ...storage.sync,
     .....
}

**Comment by sunnylqm** [comment]
哪里的key不一样？
为啥要复制一遍这样写？
如果要增加sync可以直接
storage.sync.某个新key = function () {}

**Comment by lxooxl** [comment]
我打印出的NotFoundError 那条,

**Comment by sunnylqm** [comment]
ok 那就关了
