### ISSUE TITLE
storage.remove可以一次删除多个key吗?

### ISSUE THREAD

**Issue by RealAmissio** [sunnylqm/react-native-storage#72]
storage.remove({key: 'a'},{key: 'b'},{key: 'b'},{key: 'd'});
 storage.remove([{key: 'a'},{key: 'b'},{key: 'b'},{key: 'd'}]);
这两种方法写都会报错清不掉缓存，只能 
   storage.remove({key: 'a'});
    storage.remove({key: 'b'});
    storage.remove({key: 'c});
    storage.remove({key: 'd'}),请问是我的书写格式不对吗？
我是为了做图片上传缓存，四个页面，可以公用一个key吗

**Comment by sunnylqm** [comment]
1. 不能批量删
2. 看不懂你的需求和实际key之间有什么逻辑关联

**Comment by RealAmissio** [comment]
3q，我先把逻辑理理顺

**Comment by dccmmtop** [comment]
有没有  `remove all`
