### ISSUE TITLE
storage.clearMapForKey('user')报错

### ISSUE THREAD

**Issue by Hanson2017** [sunnylqm/react-native-storage#73]
storage.clearMapForKey('user');报错 Cannot read property 'map' of undefined

**Comment by sunnylqm** [comment]
请贴代码和报错截图

**Comment by Hanson2017** [comment]
![e1097f7c-14b8-4240-942a-d11c23a8c274](https://cloud.githubusercontent.com/assets/24449780/23779775/6b3f35d2-057d-11e7-848e-58d24fa00402.png)
![7a85c12e-23ff-468c-baca-908a673a300a](https://cloud.githubusercontent.com/assets/24449780/23779776/6dc2402e-057d-11e7-9621-62f35b995595.png)
![25b46620-3387-48c0-951b-badcdcee3357](https://cloud.githubusercontent.com/assets/24449780/23779779/6f69ab10-057d-11e7-8ecd-a04dde70daa8.png)

**Comment by sunnylqm** [comment]
clearMapForKey是用于key-id数据的，不是用于key-only数据
