### ISSUE TITLE
this._s.getItem is not a function

### ISSUE THREAD

**Issue by MoutonJB** [sunnylqm/react-native-storage#75]
Hi, 

I am fairly new to react-native and just started using this library on a project to initialise my data storage. I have followed the basic instructions as outlined by the readme file just to get started but immediately get an error saying "this._s.getItem is not a function".

I created a global dataStorage.js file that contains the following:
```javascript
'use strict';

import React from 'react';
import AsyncStorage from 'react-native';
import Storage from 'react-native-storage';

var storage = new Storage({
    // Use AsyncStorage for RN, or window.localStorage for web.
    // If not set, data would be lost after reload.
    storageBackend: AsyncStorage,

    // expire time, default 1 day(1000 * 3600 * 24 milliseconds).
    // can be null, which means never expire.
    defaultExpires: null,

    // cache data in the memory. default is true.
    enableCache: true
});

global.dataStorage = storage;
```
This is then imported once in my main application file index.ios.js using the following code:
```javascript
'use strict';

import React, { Component } from 'react';
import {
    AppRegistry,
    StyleSheet,
    Navigator,
    Alert
} from 'react-native';

// Globals
import './globals/dataStorage.js'
```
Immediately when running the application I receive and error saying "this._s.getItem is not a function" which references lines 44 and 36 in the library which is:
```javascript
    me._mapPromise = me.getItem('map').then(map => {
      me._m = me._checkMap(map && JSON.parse(map) || {});
      // delete me._mapPromise;
    });
```
and
```javascript
getItem(key) {
    return this._s
      ?
      this.isPromise ? this._s.getItem(key) : Promise.resolve(this._s.getItem(key))
      :
      Promise.resolve();
  }
```
I am developing on a Mac running El Capitan 10.11.6 and Xcode 8.2.1.

Thanks in advance

**Comment by sunnylqm** [comment]
import AsyncStorage from 'react-native';

should be

import { AsyncStorage } from 'react-native';

Please read the doc carefully.

**Comment by MoutonJB** [comment]
Thank you very much, silly mistake on my part.
