### ISSUE TITLE
saveBatchData? 

### ISSUE THREAD

**Issue by pukhalski** [sunnylqm/react-native-storage#8]
Is it any chance to save a collection right away? Or should it be done item by item?

**Comment by AlexMubarakshin** [comment]
I do not know how to store the data. As long as they are stored in the "data.js"

**Comment by sunnylqm** [comment]
You can save a collection(either array or object map) into one key, or use a for loop to save them one by one in "key-id" form.

**Comment by pukhalski** [comment]
Thanks!
