### ISSUE TITLE
Config for webpack 2

### ISSUE THREAD

**Issue by harshpatel79** [sunnylqm/react-native-storage#80]
Hey folks,

I was trying to include react-native-storage module in my app using webpack2, But getting following error.

Module build failed: SyntaxError: D:/useName../../node_modules/react-native-storage/storage.js: Unexpected token (188:39) 

My config is

     `module: {
			rules: [
		        {
		          test: /\.js?$/,
		          include: [
		            path.join(__dirname, '../node_modules/react-native-storage')
		          ],
		          use: [{
		           	loader:'babel-loader',
		          	options: {
		                cacheDirectory: true,
			            presets: ['es2015','env','react'],
			            plugins: ['transform-runtime']
		            }
		          }],
		        }
		    ]
		},`

Can someone look into this and help me out in config, where I'm wrong....

**Comment by sunnylqm** [comment]
I haven't tried webpack 2 yet. I'll try it later.

**Comment by harshpatel79** [comment]
Thanks @sunnylqm , I got this...
You just need to change Presets array to presets: ['es2015','stage-1','react']

**Comment by sunnylqm** [comment]
OK.
