### ISSUE TITLE
WEB上使用时webpack打包报错

### ISSUE THREAD

**Issue by fanlide** [sunnylqm/react-native-storage#81]
是按照文档配置的，可是依然报错
error in ./~/react-native-storage/storage.js
module parse failed: ~\node_modules\react-native-storage\storage.js unexpected token (188:39)
you may need an appropriate loader to handle this file type.
整个项目都是用es6写的就这个报错

**Comment by sunnylqm** [comment]
贴一下你的配置

**Comment by fanlide** [comment]
@sunnylqm 
这是我自己的webpack和babel配置报上面那个错，后面是按你们文档配的也是报那个错
webpack：
  `{
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/,
        include: __dirname,
        query: {
          cacheDirectory: true
        }
      }`

babelrc：
 `{
  "presets": [
    [
      "latest",
      {
        "es2015": {
          "loose": true
        }
      }
    ],
    "react",
    "es2015",
    "stage-1"
  ],
  "plugins": [
    "transform-decorators-legacy",
    "mobx-deep-action",
    "syntax-decorators", [
      "transform-runtime",
      {
        "helpers": false,
        "polyfill": false,
        "regenerator": true,
        "moduleName": "babel-runtime"
      }
    ]
  ]
}`



webpack：
`{
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/,
        include: [
          path.join(__dirname, 'node_modules/react-native-storage'),
          path.join(__dirname)
        ],
        query: {
          cacheDirectory: true,
          presets: [
            'es2015', 'stage-1', 'react'
          ],
          plugins: ["transform-runtime", "transform-decorators-legacy", "mobx-deep-action", "syntax-decorators"]
        }
      }`

**Comment by sunnylqm** [comment]
exclude和include应该不能同时用吧

**Comment by fanlide** [comment]
@sunnylqm 不行，单独去掉include还是同样报上面同样的错，单独去掉exclude就是各种包在报错了……

**Comment by sunnylqm** [comment]
path.join(__dirname)  这个写法有问题？你原先写的不是 include: __dirname么？

**Comment by fanlide** [comment]
@sunnylqm 那我该怎么配置呢？我这里把include去掉后不用这个包，可以打包成功，但是一引用就会报上面那个错

**Comment by sunnylqm** [comment]
就写__dirname试试啊

**Comment by fanlide** [comment]
@sunnylqm 
然后就是这样下面这样，打包，报上面一样的错……
`{
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/,
        include: [
          path.join(__dirname, 'node_modules/react-native-storage'),
          __dirname
        ],
        query: {
          cacheDirectory: true
        }
      }`

**Comment by sunnylqm** [comment]
我说了不要同时使用exclude和include

**Comment by sunnylqm** [comment]
实在不会配置你就把storage.js放到你自己源代码里直接引用算了

**Comment by fanlide** [comment]
@sunnylqm 解决了，最终配置是这样的，另外之前说去掉include其他包各种报错，是其他包差个“babel-plugin-mobx-deep-action”包,不过为什么exclude不用这个包不会报错，不明白……
`{
        test: /\.js$/,
        loader: 'babel',
        include: __dirname,
        query: {
          cacheDirectory: true
        }
      }`

**Comment by fanlide** [comment]
@sunnylqm 谢谢解答了，用上后果然不错

**Comment by sunnylqm** [comment]
OK
