### ISSUE TITLE
和 saga 配合使用存在问题

### ISSUE THREAD

**Issue by onweer** [sunnylqm/react-native-storage#84]
![image](https://cloud.githubusercontent.com/assets/11755669/25173421/99047e6e-2526-11e7-9a4a-4f78e3f21759.png)

这样调用会报错 ：

![image](https://cloud.githubusercontent.com/assets/11755669/25173429/a58b087e-2526-11e7-8e79-c0f169140bce.png)

**Comment by sunnylqm** [comment]
看不太懂。。。不能直接调用吗

**Comment by onweer** [comment]
react native 使用了 saga。 saga 和 react-native-storage 有什么比较好的配合方案吗？

![image](https://cloud.githubusercontent.com/assets/11755669/25174000/99a3221a-2528-11e7-94ff-ed51afb133a8.png)

**Comment by sunnylqm** [comment]
以回调的方式调用就需要绑定context，我刚去看了下saga的文档，有绑定context的写法，你参考一下
https://github.com/redux-saga/redux-saga/tree/master/docs/api#callcontext-fn-args
context指定为storage即可

**Comment by onweer** [comment]
感谢，已解决：

![image](https://cloud.githubusercontent.com/assets/11755669/25210156/67188216-25b1-11e7-8851-fb9b778fca49.png)

**Comment by sunnylqm** [comment]
:) 并不需要额外写global.

**Comment by sunnylqm** [comment]
另外你的rowData好像写错了
应该是rawData

**Comment by onweer** [comment]
@sunnylqm :D，谢谢，我说执行 load 函数怎么总是 undefined 呢
