### ISSUE TITLE
写了一个Storage.JS

### ISSUE THREAD

**Issue by Rcrosp** [sunnylqm/react-native-storage#85]
```
import { AsyncStorage } from 'react-native';
import Storage from 'react-native-storage';

var storage = new Storage({
    // 最大容量，默认值1000条数据循环存储
    size: 1000,

    // 存储引擎：对于RN使用AsyncStorage，对于web使用window.localStorage
    // 如果不指定则数据只会保存在内存中，重启后即丢失
    storageBackend: AsyncStorage,

    // 数据过期时间，默认一整天（1000 * 3600 * 24 毫秒），设为null则永不过期
    defaultExpires: 1000 * 3600 * 24,

    // 读写时在内存中缓存数据。默认启用。
    enableCache: true,

    // 如果storage中没有相应数据，或数据已过期，
    // 则会调用相应的sync方法，无缝返回最新数据。
    // sync方法的具体说明会在后文提到
    // 你可以在构造函数这里就写好sync的方法
    // 或是写到另一个文件里，这里require引入
    // 或是在任何时候，直接对storage.sync进行赋值修改
    sync: require('./sync')
})

global.storage = storage;
```

在别的地方引用，出现ReferenceError: storage is not defined，在入口引用该JS直接报错，请问是什么原因

**Comment by sunnylqm** [comment]
引用报什么错

**Comment by Rcrosp** [comment]
GET http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false 500 (Internal Server Error)

**Comment by Rcrosp** [comment]
import localStorage from './app/utils/RTStorage';

**Comment by Rcrosp** [comment]
import storage from './app/utils/RTStorage';

**Comment by sunnylqm** [comment]
截图贴出来

**Comment by sunnylqm** [comment]
import报错   99%的可能就是路径错了
另外你这里只需要import  不需要from  因为并没有export

**Comment by Rcrosp** [comment]
import 路径？

**Comment by sunnylqm** [comment]
import '路径'

**Comment by Rcrosp** [comment]
还是出错
![wechatimg1](https://cloud.githubusercontent.com/assets/8972396/25213192/6f48bffe-25c1-11e7-9cfe-b64e5d52a11a.jpeg)

**Comment by sunnylqm** [comment]
删掉node_modules重新npm install

**Comment by Rcrosp** [comment]
还是一样

**Comment by sunnylqm** [comment]
关闭debug再看

**Comment by Rcrosp** [comment]
bundling: UnableToResolveError: Unable to resolve module `./sync` from `/Users/.../app/utils/RTStorage.js`

**Comment by Rcrosp** [comment]
Cannot read property 'toString' of undefined

**Comment by Rcrosp** [comment]
storage.save({
                        deviceId:"789",
                        token:"456",
                        uid:"123"

                    })

**Comment by Rcrosp** [comment]
storage.save({
                        deviceId:'789',
                        token:'456',
                        uid:'123'

                    });
Cannot read property 'toString' of undefined

**Comment by sunnylqm** [comment]
请仔细先看看文档吧

**Comment by Rcrosp** [comment]
解决了，thx
