### ISSUE TITLE
Can it save an array of objects? or it just can save objects? 

### ISSUE THREAD

**Issue by XIAOYAYAYAYA** [sunnylqm/react-native-storage#86]
Because I need to save an array of objects , just like this:
var items = [{name:'a1' , age:'b1'},
                      {name:'a2' , age:'b2'},
                        {name:'a3' , age:'b3'}]             ]
Can it save an array of objects? or it just can save objects? 
Does anyone know this point?  if it can't, is there some anther methods to  realize this point ?
Thank you very much~

**Comment by sunnylqm** [comment]
That's OK.

**Comment by XIAOYAYAYAYA** [comment]
Thanks a lot, I will have a try~@sunnylqm
