### ISSUE TITLE
现在想用这个实现listview的数据增删改查，其中每一条数据需跳转到详细界面完成编辑功能

### ISSUE THREAD

**Issue by XIAOYAYAYAYA** [sunnylqm/react-native-storage#88]
由于数据需要完成编辑功能，所以每一条数据需要一一对应序号id，但是在删除数据时候，id会缺少一条，所以需要对数据进行重新排序，以下是删除条目，以及listview 数据刷新的逻辑，
deleteGood(rowID, rowData) {
        storage.remove({//删除Listview 的某一条数据
            key: 'goods',
            id: rowID,
        }).then(
            storage.getAllDataForKey('goods').then(goods => {
                // 获取storage当前所有数据
                let items = [];
                storage.clearMapForKey('goods');// 清空storage当前所有数据
                for (let i = 0; i < goods.length; i++) {
                    //将当前数据重新编排id保存
                    items.push(goods[i]);
                    console.log(`数据--${String(i)}--${goods[i].name}`);
                    storage.save({
                        key: 'goods',
                        id: String(i),
                        rawData: goods[i],
                    }).then(
                        console.log(`数据${String(i)}--${goods[i].name}`)
                    )
                }
                storage.getAllDataForKey('goods').then(goods => {
                    console.log(goods);
                })
                d.setState({
                    dataLength: items.length,
                    dataSource: d.state.dataSource.cloneWithRows(items)//刷新数据显示
                })
            })
        )
    }
问题是   for循环里的保存操作只执行一次，为啥啊？求大神帮帮我啊。。

**Comment by XIAOYAYAYAYA** [comment]
log：数据--0--苹果22
数据0--苹果22
数据--1--苹果33
数据1--苹果33
[0]

我的数据源是 id 为0 的苹果11，id 为1 的苹果22，id 为2苹果33，执行删除苹果11操作后，log显示save的操作都成功了    但是 只保存了一条 id为0 的苹果22

**Comment by sunnylqm** [comment]
插断点调吧，这些业务逻辑恕无时间奉陪。
