### ISSUE TITLE
封装后，load数据提示为undefine

### ISSUE THREAD

**Issue by LeesinYasuo** [sunnylqm/react-native-storage#90]
你好，
   请问为和我封装一层，之后load数据老是提示为undefine阿，不封装又可以正常load数据，有趣的是我在同一类中封装成一个函数，load正常，但是当我将其单独封装到另外一个Utils类中就load提示undefine，可以帮忙解答下吗？
 封装如下，这样保存之后load提示undefined
export default class FavoriteDao {
   save(key,id,rowData){
      storage.save({key:key,id:id,rowData:rowData});
  }

**Comment by sunnylqm** [comment]
是`rawData` 不是rowData
