### ISSUE TITLE
请问在key-id的组合中如何传递参数给sync函数？

### ISSUE THREAD

**Issue by LeesinYasuo** [sunnylqm/react-native-storage#91]
你好，
   请问在key-id的组合中如何传递参数给sync函数？如果是key组合，可以通过load函数里面传参数，但是
如何通过getAllDataForKey函数来传递参数呢？
   export default function hot(params) {
    let { syncParams: {tabLabel} } = params;
    fetch(`https://api.github.com/search/repositories?q=${tabLabel}&sort=stars`)

**Comment by sunnylqm** [comment]
目前没有传递参数，你可以看看源码改一下
https://github.com/sunnylqm/react-native-storage/blob/master/storage.js#L331

**Comment by LeesinYasuo** [comment]
hao de
