### ISSUE TITLE
未做判空处理

### ISSUE THREAD

**Issue by whj5484138** [sunnylqm/react-native-storage#94]
clearMapForKey(key) {
    return this._mapPromise.then(() => {
      let tasks = this._m.__keys__[key].map(id => this.remove({ key, id }));
      return Promise.all(tasks);
    });
  }
  
  如果对应key的数据为空时，调用map方法会报错，最好加个安全策略吧

**Comment by sunnylqm** [comment]
可以麻烦给个pr么

**Comment by whj5484138** [comment]
已经给了 请check下

**Comment by sunnylqm** [comment]
感谢
