### ISSUE TITLE
how to mock react-native-storage with jest ?

### ISSUE THREAD

**Issue by jcharlet** [sunnylqm/react-native-storage#95]
Hi,
I'm trying to set up unit tests like I did previously with AsyncStorage using solution from https://codedump.io/share/o9BwTxPB0R7o/1/how-to-test-async-storage-with-jest

but when I mock 'AsyncStorage' (that I use in your system's configuration), I still get the following error:
Failed: RCTAsyncStorage.multiSet is not a function

so it seems the mock is being bypassed.
Any idea whether it's possible, have you done it?
Thanks,
Jeremie

**Comment by sunnylqm** [comment]
I was mocking it in a way like the answer in your link
https://github.com/sunnylqm/react-native-storage/blob/master/jestSupport/mockStorage.js

**Comment by jcharlet** [comment]
thank you so much for your quick answer, I've spent so much time trying to do it, and managed to init your mock in setupFiles like you did. works like a charm!
