### ISSUE TITLE
cannot find variable:storage

### ISSUE THREAD

**Issue by nostale** [sunnylqm/react-native-storage#96]
根据文档步骤走了一遍，发现在sync: require('./sync') 出现问题

![626620fc-5dd9-4f42-bf3f-5aa4fda4974c](https://cloud.githubusercontent.com/assets/28687632/26034708/329026c0-38f3-11e7-8910-07a5c54ccdf1.png)

sync.js:
![05840387-5e2f-43ca-b540-97d493b4e9f6](https://cloud.githubusercontent.com/assets/28687632/26034724/74d92658-38f3-11e7-9ae1-0f4f78aa696a.png)

**Comment by sunnylqm** [comment]
你这是陷入了一个鸡生蛋蛋生鸡的死循环啊。。。
storage的构造函数等待sync，sync里又等待storage。。。
我文档里举的例子是先构造完了storage，再给storage添加sync子属性
如果你直接在storage中构造sync并放在单独的模块里，那就
```
// 这里是sync.js的内容
// 构造一个名字叫sync的对象，其中包含了各种同步方法逻辑
const sync = {
  user(params) { ... }
  同步方法2,
  同步方法3,
  ......
}
module.exports = sync;  // 把这个sync对象导出，以便在storage中require引用
```

**Comment by nostale** [comment]
明白了，非常感谢。 @sunnylqm
